### ISSUE TITLE
Fehler beim backup mit docker

### ISSUE THREAD

**Issue by cburghardt** [simatec/ioBroker.backitup#1002]
Der folgende Fehler kommt jeden Tag beim automatischen Backup:

```
backitup.0
2023-10-08 03:30:17.275	error	[iobroker/clean] Backup files not deleted from /opt/iobroker/backups because some errors.
backitup.0
2023-10-08 03:30:13.551	error	[iobroker/googledrive] Google Drive: File "/opt/iobroker/backups/iobroker_2023_10_08-03_30_10_backupiobroker.tar.gz" not found
backitup.0
2023-10-08 03:30:10.512	error	[iobroker/iobroker] Node.js v18.17.1
backitup.0
2023-10-08 03:30:10.512	error	[iobroker/iobroker] }
backitup.0
2023-10-08 03:30:10.512	error	[iobroker/iobroker] syscall: 'uv_cwd'
backitup.0
2023-10-08 03:30:10.511	error	[iobroker/iobroker] code: 'ENOENT',
backitup.0
2023-10-08 03:30:10.511	error	[iobroker/iobroker] errno: -2,
backitup.0
2023-10-08 03:30:10.511	error	[iobroker/iobroker] at Module.require (node:internal/modules/cjs/loader:1143:19) {
backitup.0
2023-10-08 03:30:10.511	error	[iobroker/iobroker] at Module._load (node:internal/modules/cjs/loader:960:12)
backitup.0
2023-10-08 03:30:10.511	error	[iobroker/iobroker] at Module.load (node:internal/modules/cjs/loader:1119:32)
backitup.0
2023-10-08 03:30:10.511	error	[iobroker/iobroker] at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
backitup.0
2023-10-08 03:30:10.511	error	[iobroker/iobroker] at Module._compile (node:internal/modules/cjs/loader:1256:14)
backitup.0
2023-10-08 03:30:10.511	error	[iobroker/iobroker] at Object.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-cli/node_modules/yargs/index.cjs:7:1)
backitup.0
2023-10-08 03:30:10.511	error	[iobroker/iobroker] at Argv (/opt/iobroker/node_modules/@iobroker/js-controller-cli/node_modules/yargs/index.cjs:12:16)
backitup.0
2023-10-08 03:30:10.511	error	[iobroker/iobroker] at ue.Yargs (/opt/iobroker/node_modules/@iobroker/js-controller-cli/node_modules/yargs/build/index.cjs:1:61943)
backitup.0
2023-10-08 03:30:10.511	error	[iobroker/iobroker] at process.cwd (/opt/iobroker/node_modules/graceful-fs/polyfills.js:10:19)
backitup.0
2023-10-08 03:30:10.511	error	[iobroker/iobroker] at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:126:28)
backitup.0
2023-10-08 03:30:10.510	error	[iobroker/iobroker] Error: ENOENT: no such file or directory, uv_cwd
backitup.0
2023-10-08 03:30:10.510	error	[iobroker/iobroker] ^
backitup.0
2023-10-08 03:30:10.510	error	[iobroker/iobroker] cachedCwd = rawMethods.cwd();
backitup.0
2023-10-08 03:30:10.508	error	[iobroker/iobroker] node:internal/bootstrap/switches/does_own_process_state:126

```

iobroker läuft im container auf docker.
Der Fehler verschwindet für ein paar Tage, wenn ich den container durchstarte, kommt dann aber wieder.
backitup: 2.8.2
controller: 5.0.12

**Comment by simatec** [comment]
Dies ist leider ein bekannter Node Bug und ist nicht in der Macht von Backitup. 
Workaround
Stelle Backitup im Admin so ein, dass er einmal am Tag neugestartet wird.
