### ISSUE TITLE
Honour /etc/fstab for mounting without sudo/root privileges

### ISSUE THREAD

**Issue by Grothesk242** [simatec/ioBroker.backitup#1003]
I have a working entry in my /etc/fstab that allows the user 'iobroker' to mount a cifs filesystem into /opt/iobroker/backups
Backitup does not use this entry but does a 'manual mount' with full options and does not rely on the fstab. 

Can you make the code more simple? 
A checkbox like 'Mount via /etc/fstab' would be great.

**Comment by simatec** [comment]
Can you please post here how the mount should look like?

**Comment by Grothesk242** [comment]
```
//HOST/path/to/remote/backup /opt/iobroker/backups  cifs credentials=/home/iobroker/.smbcredentials,users,noserverino,rw,noauto,uid=iobroker,gid=iobroker,file_mode=0777,dir_mode=0777          0      0
```
ist mountable by user 'iobroker' because of the Option 'users'
.smbcredentials contains: 

```
username=USERNAME_on_SMB-Server
password=S3Cre7_p4$$w0r8
```

**Comment by simatec** [comment]
If we include these expert settings, I would like to do it for CIFS and NFS.
We would now have to see how to combine this in the most sensible way.

**Comment by simatec** [comment]
In v2.10.7 added

**Comment by Grothesk242** [comment]
Tested, LGTM.

**Comment by Grothesk242** [comment]
Additional testing showed crashes when ExpertMode is activated. 
Option set was: 

``sudo -u iobroker mount /opt/iobroker/backups``
This command works flawlessly in CLI. 

Crash:
```
2024-01-29 23:34:53.123  - debug: backitup.0 (37899) Redis Objects: Use Redis connection: 0.0.0.0:9001
2024-01-29 23:34:53.225  - debug: backitup.0 (37899) Objects client ready ... initialize now
2024-01-29 23:34:53.233  - debug: backitup.0 (37899) Objects create System PubSub Client
2024-01-29 23:34:53.236  - debug: backitup.0 (37899) Objects create User PubSub Client
2024-01-29 23:34:53.329  - debug: backitup.0 (37899) Objects client initialize lua scripts
2024-01-29 23:34:53.341  - debug: backitup.0 (37899) Objects connected to redis: 0.0.0.0:9001
2024-01-29 23:34:53.394  - debug: backitup.0 (37899) Redis States: Use Redis connection: 0.0.0.0:9000
2024-01-29 23:34:53.423  - debug: backitup.0 (37899) States create System PubSub Client
2024-01-29 23:34:53.426  - debug: backitup.0 (37899) States create User PubSub Client
2024-01-29 23:34:53.519  - debug: backitup.0 (37899) States connected to redis: 0.0.0.0:9000
2024-01-29 23:34:53.583  - debug: backitup.0 (37899) Plugin sentry Do not initialize Plugin (enabled=false)
2024-01-29 23:34:53.634  - debug: backitup.0 (37899) Plugin sentry destroyed because not initialized correctly
2024-01-29 23:34:54.024  - info: backitup.0 (37899) starting. Version 2.10.7 in /opt/iobroker/node_modules/iobroker.backitup, node: v21.6.1, js-controller: 5.0.17
2024-01-29 23:34:54.092  - debug: backitup.0 (37899) Backitup has recognized a linux system
2024-01-29 23:34:54.121  - info: backitup.0 (37899) [iobroker] backup will be activated at 03:42 every 1 day(s)
2024-01-29 23:34:53.123  - debug: backitup.0 (37899) Redis Objects: Use Redis connection: 0.0.0.0:9001
2024-01-29 23:34:53.225  - debug: backitup.0 (37899) Objects client ready ... initialize now
2024-01-29 23:34:53.233  - debug: backitup.0 (37899) Objects create System PubSub Client
2024-01-29 23:34:53.236  - debug: backitup.0 (37899) Objects create User PubSub Client
2024-01-29 23:34:53.329  - debug: backitup.0 (37899) Objects client initialize lua scripts
2024-01-29 23:34:53.341  - debug: backitup.0 (37899) Objects connected to redis: 0.0.0.0:9001
2024-01-29 23:34:53.394  - debug: backitup.0 (37899) Redis States: Use Redis connection: 0.0.0.0:9000
2024-01-29 23:34:53.423  - debug: backitup.0 (37899) States create System PubSub Client
2024-01-29 23:34:53.426  - debug: backitup.0 (37899) States create User PubSub Client
2024-01-29 23:34:53.519  - debug: backitup.0 (37899) States connected to redis: 0.0.0.0:9000
2024-01-29 23:34:53.583  - debug: backitup.0 (37899) Plugin sentry Do not initialize Plugin (enabled=false)
2024-01-29 23:34:53.634  - debug: backitup.0 (37899) Plugin sentry destroyed because not initialized correctly
2024-01-29 23:34:54.024  - info: backitup.0 (37899) starting. Version 2.10.7 in /opt/iobroker/node_modules/iobroker.backitup, node: v21.6.1, js-controller: 5.0.17
2024-01-29 23:34:54.092  - debug: backitup.0 (37899) Backitup has recognized a linux system
2024-01-29 23:34:54.121  - info: backitup.0 (37899) [iobroker] backup will be activated at 03:42 every 1 day(s)
2024-01-29 23:34:54.193  - debug: backitup.0 (37899) expert-mount command: "undefined"
2024-01-29 23:34:55.081  - error: backitup.0 (37899) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-01-29 23:34:55.082  - error: backitup.0 (37899) unhandled promise rejection: The "command" argument must be of type string. Received undefined
2024-01-29 23:34:55.083  - error: backitup.0 (37899) TypeError [ERR_INVALID_ARG_TYPE]: The "command" argument must be of type string. Received undefined
    at normalizeExecArgs (node:child_process:190:3)
    at Object.exec (node:child_process:233:16)
    at mount (/opt/iobroker/node_modules/iobroker.backitup/lib/list/cifs.js:219:23)
    at Object.list (/opt/iobroker/node_modules/iobroker.backitup/lib/list/cifs.js:11:13)
    at module.exports (/opt/iobroker/node_modules/iobroker.backitup/lib/list.js:76:36)
    at /opt/iobroker/node_modules/iobroker.backitup/main.js:1413:17
    at new Promise (<anonymous>)
    at /opt/iobroker/node_modules/iobroker.backitup/main.js:1412:46
    at Array.map (<anonymous>)
    at detectLatestBackupFile (/opt/iobroker/node_modules/iobroker.backitup/main.js:1412:31)
2024-01-29 23:34:55.083  - error: backitup.0 (37899) Exception-Code: ERR_INVALID_ARG_TYPE: The "command" argument must be of type string. Received undefined
2024-01-29 23:34:55.127  - info: backitup.0 (37899) cleaned everything up...
2024-01-29 23:34:55.128  - info: backitup.0 (37899) terminating
2024-01-29 23:34:55.129  - warn: backitup.0 (37899) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-01-29 23:34:55.632  - info: backitup.0 (37899) terminating
2024-01-29 23:34:55.753  - error: host.chet Caught by controller[0]: (node:37899) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
2024-01-29 23:34:55.757  - error: host.chet Caught by controller[0]: (Use `node --trace-deprecation ...` to show where the warning was created)
2024-01-29 23:34:55.757  - error: host.chet instance system.adapter.backitup.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-01-29 23:34:54.193  - debug: backitup.0 (37899) expert-mount command: "undefined"
2024-01-29 23:34:55.081  - error: backitup.0 (37899) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-01-29 23:34:55.082  - error: backitup.0 (37899) unhandled promise rejection: The "command" argument must be of type string. Received undefined
2024-01-29 23:34:55.083  - error: backitup.0 (37899) TypeError [ERR_INVALID_ARG_TYPE]: The "command" argument must be of type string. Received undefined
    at normalizeExecArgs (node:child_process:190:3)
    at Object.exec (node:child_process:233:16)
    at mount (/opt/iobroker/node_modules/iobroker.backitup/lib/list/cifs.js:219:23)
    at Object.list (/opt/iobroker/node_modules/iobroker.backitup/lib/list/cifs.js:11:13)
    at module.exports (/opt/iobroker/node_modules/iobroker.backitup/lib/list.js:76:36)
    at /opt/iobroker/node_modules/iobroker.backitup/main.js:1413:17
    at new Promise (<anonymous>)
    at /opt/iobroker/node_modules/iobroker.backitup/main.js:1412:46
    at Array.map (<anonymous>)
    at detectLatestBackupFile (/opt/iobroker/node_modules/iobroker.backitup/main.js:1412:31)
2024-01-29 23:34:55.083  - error: backitup.0 (37899) Exception-Code: ERR_INVALID_ARG_TYPE: The "command" argument must be of type string. Received undefined
2024-01-29 23:34:55.127  - info: backitup.0 (37899) cleaned everything up...
2024-01-29 23:34:55.128  - info: backitup.0 (37899) terminating
2024-01-29 23:34:55.129  - warn: backitup.0 (37899) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-01-29 23:34:55.632  - info: backitup.0 (37899) terminating
2024-01-29 23:34:55.753  - error: host.chet Caught by controller[0]: (node:37899) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
2024-01-29 23:34:55.757  - error: host.chet Caught by controller[0]: (Use `node --trace-deprecation ...` to show where the warning was created)
2024-01-29 23:34:55.757  - error: host.chet instance system.adapter.backitup.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
```
