### ISSUE TITLE
Error during backup

### ISSUE THREAD

**Issue by walburgf** [simatec/ioBroker.backitup#1134]
**Describe the bug**  
The following error messages are shown in the backup log:
````
2024-06-23 09:07:05.597 - error: backitup.1 (1634) [iobroker/iobroker] node:internal/bootstrap/switches/does_own_process_state:144
--
2024-06-23 09:07:05.598 - error: backitup.1 (1634) [iobroker/iobroker] cachedCwd = rawMethods.cwd();
2024-06-23 09:07:05.598 - error: backitup.1 (1634) [iobroker/iobroker] ^
2024-06-23 09:07:05.598 - error: backitup.1 (1634) [iobroker/iobroker] Error: ENOENT: no such file or directory, uv_cwd
2024-06-23 09:07:05.598 - error: backitup.1 (1634) [iobroker/iobroker] at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:144:28)
2024-06-23 09:07:05.598 - error: backitup.1 (1634) [iobroker/iobroker] at process.cwd (/opt/iobroker/node_modules/graceful-fs/polyfills.js:10:19)
2024-06-23 09:07:05.598 - error: backitup.1 (1634) [iobroker/iobroker] at Object. (/opt/iobroker/node_modules/yargs/build/index.cjs:1:60970)
2024-06-23 09:07:05.598 - error: backitup.1 (1634) [iobroker/iobroker] at Module._compile (node:internal/modules/cjs/loader:1358:14)
2024-06-23 09:07:05.598 - error: backitup.1 (1634) [iobroker/iobroker] at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
2024-06-23 09:07:05.598 - error: backitup.1 (1634) [iobroker/iobroker] at Module.load (node:internal/modules/cjs/loader:1208:32)
2024-06-23 09:07:05.598 - error: backitup.1 (1634) [iobroker/iobroker] at Module._load (node:internal/modules/cjs/loader:1024:12)
2024-06-23 09:07:05.598 - error: backitup.1 (1634) [iobroker/iobroker] at cjsLoader (node:internal/modules/esm/translators:348:17)
2024-06-23 09:07:05.598 - error: backitup.1 (1634) [iobroker/iobroker] at ModuleWrap. (node:internal/modules/esm/translators:297:7)
2024-06-23 09:07:05.598 - error: backitup.1 (1634) [iobroker/iobroker] at ModuleJob.run (node:internal/modules/esm/module_job:222:25) {
2024-06-23 09:07:05.598 - error: backitup.1 (1634) [iobroker/iobroker] errno: -2,
2024-06-23 09:07:05.599 - error: backitup.1 (1634) [iobroker/iobroker] code: 'ENOENT',
2024-06-23 09:07:05.599 - error: backitup.1 (1634) [iobroker/iobroker] syscall: 'uv_cwd'
2024-06-23 09:07:05.599 - error: backitup.1 (1634) [iobroker/iobroker] }
2024-06-23 09:07:05.599 - error: backitup.1 (1634) [iobroker/iobroker] Node.js v20.13.1
2024-06-23 09:07:10.811 - error: backitup.1 (1634) [iobroker/onedrive] Onedrive: File "/opt/iobroker/backups/iobroker_2024_06_23-09_07_05_backupiobroker.tar.gz" not found
2024-06-23 09:07:11.927 - error: backitup.1 (1634) [iobroker/googledrive] Google Drive: File "/opt/iobroker/backups/iobroker_2024_06_23-09_07_05_backupiobroker.tar.gz" not found
2024-06-23 09:07:14.553 - error: backitup.1 (1634) [iobroker/clean] Backup files not deleted from /opt/iobroker/backups because some errors.
````

**To Reproduce**  
1. Create a backup with the following options activated:
- backup ioBroker and Javascript
- destinations: google drive and onedrive

**Expected behavior**  
no error messages in the logfile

**Screenshots & Logfiles**  
see above

**Versions:**  
 - Adapter version: 3.0.5
 - JS-Controller version: 6.0.5 
 - Node version: 20.13.1 
 - Operating system: Debian 12.5 and Debian 11 (within Proxmox 8.2.4)

**Additional context**

**Comment by walburgf** [comment]
ater upgrading to Debian 12 (bookworm), everything is working correct.... Bug may be closed....

**Comment by walburgf** [comment]
it seems, that debian bookworm is necessary for the correct functionaility

**Comment by walburgf** [comment]
after upgrading to bookworm, the backup only worked once, then the same error happens again

**Comment by simatec** [comment]
Please restart your System...

**Comment by simatec** [comment]
Test with v3.0.7

**Comment by walburgf** [comment]
**I upgraded to v3.0.7 yesterday and did a reboot of the machine.
After starting a manual backup, everything seems to work fine.

This night, a scheduled backup was initiated, and the same issue happen again.
Here is the log entry:**

2024-06-27 08:26:38.174 - error: backitup.1 (1407) [iobroker/iobroker] node:internal/bootstrap/switches/does_own_process_state:144
2024-06-27 08:26:38.174 - error: backitup.1 (1407) [iobroker/iobroker] cachedCwd = rawMethods.cwd();
2024-06-27 08:26:38.174 - error: backitup.1 (1407) [iobroker/iobroker] ^
2024-06-27 08:26:38.174 - error: backitup.1 (1407) [iobroker/iobroker] Error: ENOENT: no such file or directory, uv_cwd
2024-06-27 08:26:38.174 - error: backitup.1 (1407) [iobroker/iobroker] at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:144:28)
2024-06-27 08:26:38.174 - error: backitup.1 (1407) [iobroker/iobroker] at process.cwd (/opt/iobroker/node_modules/graceful-fs/polyfills.js:10:19)
2024-06-27 08:26:38.174 - error: backitup.1 (1407) [iobroker/iobroker] at Object. (/opt/iobroker/node_modules/yargs/build/index.cjs:1:60970)
2024-06-27 08:26:38.174 - error: backitup.1 (1407) [iobroker/iobroker] at Module._compile (node:internal/modules/cjs/loader:1358:14)
2024-06-27 08:26:38.174 - error: backitup.1 (1407) [iobroker/iobroker] at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
2024-06-27 08:26:38.174 - error: backitup.1 (1407) [iobroker/iobroker] at Module.load (node:internal/modules/cjs/loader:1208:32)
2024-06-27 08:26:38.174 - error: backitup.1 (1407) [iobroker/iobroker] at Module._load (node:internal/modules/cjs/loader:1024:12)
2024-06-27 08:26:38.174 - error: backitup.1 (1407) [iobroker/iobroker] at cjsLoader (node:internal/modules/esm/translators:348:17)
2024-06-27 08:26:38.174 - error: backitup.1 (1407) [iobroker/iobroker] at ModuleWrap. (node:internal/modules/esm/translators:297:7)
2024-06-27 08:26:38.174 - error: backitup.1 (1407) [iobroker/iobroker] at ModuleJob.run (node:internal/modules/esm/module_job:222:25) {
2024-06-27 08:26:38.174 - error: backitup.1 (1407) [iobroker/iobroker] errno: -2,
2024-06-27 08:26:38.174 - error: backitup.1 (1407) [iobroker/iobroker] code: 'ENOENT',
2024-06-27 08:26:38.174 - error: backitup.1 (1407) [iobroker/iobroker] syscall: 'uv_cwd'
2024-06-27 08:26:38.174 - error: backitup.1 (1407) [iobroker/iobroker] }
2024-06-27 08:26:38.174 - error: backitup.1 (1407) [iobroker/iobroker] Node.js v20.15.0
2024-06-27 08:26:43.828 - error: backitup.1 (1407) [iobroker/onedrive] Onedrive: File "/opt/iobroker/backups/iobroker_2024_06_27-08_26_38_backupiobroker.tar.gz" not found
2024-06-27 08:26:45.445 - error: backitup.1 (1407) [iobroker/googledrive] Google Drive: File "/opt/iobroker/backups/iobroker_2024_06_27-08_26_38_backupiobroker.tar.gz" not found
2024-06-27 08:26:48.441 - error: backitup.1 (1407) [iobroker/clean] Backup files not deleted from /opt/iobroker/backups because some errors.

**The log of the manual backup now also shows errors:**

Backitup-Ausführung:
08:30:38.449INFOguiBackup gestartet ...
08:30:38.861DEBUGiobrokerdone
08:30:40.607DEBUGjavascriptsCreated javascript_tmp directory: "/opt/iobroker/backups/tmpScripts"
08:30:42.339DEBUGjavascriptsfound Script: _Test
08:30:42.465DEBUGjavascriptsTry deleting the Javascript tmp directory: "/opt/iobroker/backups/tmpScripts"
08:30:42.508DEBUGjavascriptsdone
08:30:43.878ERRORonedriveOnedrive: File "/opt/iobroker/backups/iobroker_2024_06_27-08_30_40_backupiobroker.tar.gz" not found
08:30:43.884DEBUGonedriveOnedrive: Copy javascripts_2024_06_27-08_30_42_backupiobroker.tar.gz...
08:30:44.607DEBUGonedrive100% uploaded from javascripts_2024_06_27-08_30_42_backupiobroker.tar.gz
08:30:44.647DEBUGonedrivejavascripts_2024_06_27-08_30_42_backupiobroker.tar.gz with Id: 8F5D95BD4CB47FC!714262 saved on Onedrive
08:30:44.649DEBUGonedrivedone
08:30:45.226ERRORgoogledriveGoogle Drive: File "/opt/iobroker/backups/iobroker_2024_06_27-08_30_40_backupiobroker.tar.gz" not found
08:30:45.359DEBUGgoogledriveGoogle Drive: Copy javascripts_2024_06_27-08_30_42_backupiobroker.tar.gz...
08:30:50.375DEBUGgoogledrivedone
08:30:50.545ERRORcleanBackup files not deleted from /opt/iobroker/backups because some errors.
08:30:50.565DEBUGcleandone
08:30:50.676DEBUGhistoryHTMLnew history html values created
08:30:50.717DEBUGhistoryHTMLdone
08:30:50.870DEBUGhistoryJSONnew history json values created
08:30:50.912DEBUGhistoryJSONdone
08:30:53.376DEBUGnotificationAdmin notification will be sent
08:30:53.416DEBUGnotificationdone
08:30:53.525WARNguiDas Backup konnte nicht vollständig erstellt werden!

**Comment by walburgf** [comment]
After doing a reboot again, the manual backup was working correct, without errors.....

**Comment by walburgf** [comment]
also the scheduled backup was now running correctly again....

My assumption is, that by tommorrow, the errors appear again....

**Comment by walburgf** [comment]
another "Warning" in the logfile was written, when changing the time of the scheduled backup:

2024-06-27 08:53:02.883 - warn: admin.0 (154) backitup has an invalid jsonConfig: [{"instancePath":"/items/_options","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/then/required","keyword":"required","params":{"missingProperty":"items"},"message":"must have required property 'items'"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]

**Comment by simatec** [comment]
> also the scheduled backup was now running correctly again....
> 
> My assumption is, that by tommorrow, the errors appear again....

Which version is installed? In v3.0.7 I have made some adjustments to this Nodejs bug.

**Comment by simatec** [comment]
> another "Warning" in the logfile was written, when changing the time of the scheduled backup:
> 
> 2024-06-27 08:53:02.883 - warn: admin.0 (154) backitup has an invalid jsonConfig: [{"instancePath":"/items/_options","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/then/required","keyword":"required","params":{"missingProperty":"items"},"message":"must have required property 'items'"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match "then" schema"}]
> 
> Admin adapter is v7.0.7

Please ignore... The message comes from the admin and will be fixed in the next admin versions.

@GermanBluefox is already aware of this warning.

**Comment by walburgf** [comment]
All tests have been done with v3.0.7

**Comment by simatec** [comment]
> All tests have been done with v3.0.7

v3.0.7 is the right choice

**Comment by walburgf** [comment]
during the last 2 days, no error has occured... so it seems to work now....
I would like to wait another 2-3 days, the I think we can close the ticket....

**Comment by walburgf** [comment]
after 3 days with no errors, the issue occured again. Here is the log:

2024-07-01 02:40:10.342 - error: backitup.1 (241) [iobroker/iobroker] node:internal/bootstrap/switches/does_own_process_state:144
2024-07-01 02:40:10.346 - error: backitup.1 (241) [iobroker/iobroker] cachedCwd = rawMethods.cwd();
2024-07-01 02:40:10.346 - error: backitup.1 (241) [iobroker/iobroker] ^
2024-07-01 02:40:10.346 - error: backitup.1 (241) [iobroker/iobroker] Error: ENOENT: no such file or directory, uv_cwd
2024-07-01 02:40:10.346 - error: backitup.1 (241) [iobroker/iobroker] at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:144:28)
2024-07-01 02:40:10.346 - error: backitup.1 (241) [iobroker/iobroker] at process.cwd (/opt/iobroker/node_modules/graceful-fs/polyfills.js:10:19)
2024-07-01 02:40:10.346 - error: backitup.1 (241) [iobroker/iobroker] at Object. (/opt/iobroker/node_modules/yargs/build/index.cjs:1:60970)
2024-07-01 02:40:10.346 - error: backitup.1 (241) [iobroker/iobroker] at Module._compile (node:internal/modules/cjs/loader:1358:14)
2024-07-01 02:40:10.346 - error: backitup.1 (241) [iobroker/iobroker] at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
2024-07-01 02:40:10.346 - error: backitup.1 (241) [iobroker/iobroker] at Module.load (node:internal/modules/cjs/loader:1208:32)
2024-07-01 02:40:10.346 - error: backitup.1 (241) [iobroker/iobroker] at Module._load (node:internal/modules/cjs/loader:1024:12)
2024-07-01 02:40:10.346 - error: backitup.1 (241) [iobroker/iobroker] at cjsLoader (node:internal/modules/esm/translators:348:17)
2024-07-01 02:40:10.346 - error: backitup.1 (241) [iobroker/iobroker] at ModuleWrap. (node:internal/modules/esm/translators:297:7)
2024-07-01 02:40:10.346 - error: backitup.1 (241) [iobroker/iobroker] at ModuleJob.run (node:internal/modules/esm/module_job:222:25) {
2024-07-01 02:40:10.346 - error: backitup.1 (241) [iobroker/iobroker] errno: -2,
2024-07-01 02:40:10.346 - error: backitup.1 (241) [iobroker/iobroker] code: 'ENOENT',
2024-07-01 02:40:10.346 - error: backitup.1 (241) [iobroker/iobroker] syscall: 'uv_cwd'
2024-07-01 02:40:10.346 - error: backitup.1 (241) [iobroker/iobroker] }
2024-07-01 02:40:10.346 - error: backitup.1 (241) [iobroker/iobroker] Node.js v20.15.0
2024-07-01 02:40:15.584 - error: backitup.1 (241) [iobroker/onedrive] Onedrive: File "/opt/iobroker/backups/iobroker_2024_07_01-02_40_10_backupiobroker.tar.gz" not found
2024-07-01 02:40:17.514 - error: backitup.1 (241) [iobroker/googledrive] Google Drive: File "/opt/iobroker/backups/iobroker_2024_07_01-02_40_10_backupiobroker.tar.gz" not found
2024-07-01 02:40:21.370 - error: backitup.1 (241) [iobroker/clean] Backup files not deleted from /opt/iobroker/backups because some errors.

**Comment by simatec** [comment]
Please test v3.0.8

**Comment by walburgf** [comment]
I just installed v3.0.8. The backup is working correct.
Let's wait some days now, if the error occurs again...
Thank you....

**Comment by walburgf** [comment]
The error was now happening again with v3.0.8:


2024-07-03 02:40:10.363 - error: backitup.1 (7099) [iobroker/iobroker] node:internal/bootstrap/switches/does_own_process_state:144
2024-07-03 02:40:10.366 - error: backitup.1 (7099) [iobroker/iobroker] cachedCwd = rawMethods.cwd();
2024-07-03 02:40:10.366 - error: backitup.1 (7099) [iobroker/iobroker] ^
2024-07-03 02:40:10.366 - error: backitup.1 (7099) [iobroker/iobroker] Error: ENOENT: no such file or directory, uv_cwd
2024-07-03 02:40:10.366 - error: backitup.1 (7099) [iobroker/iobroker] at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:144:28)
2024-07-03 02:40:10.366 - error: backitup.1 (7099) [iobroker/iobroker] at process.cwd (/opt/iobroker/node_modules/graceful-fs/polyfills.js:10:19)
2024-07-03 02:40:10.366 - error: backitup.1 (7099) [iobroker/iobroker] at Object. (/opt/iobroker/node_modules/yargs/build/index.cjs:1:60970)
2024-07-03 02:40:10.366 - error: backitup.1 (7099) [iobroker/iobroker] at Module._compile (node:internal/modules/cjs/loader:1358:14)
2024-07-03 02:40:10.366 - error: backitup.1 (7099) [iobroker/iobroker] at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
2024-07-03 02:40:10.366 - error: backitup.1 (7099) [iobroker/iobroker] at Module.load (node:internal/modules/cjs/loader:1208:32)
2024-07-03 02:40:10.366 - error: backitup.1 (7099) [iobroker/iobroker] at Module._load (node:internal/modules/cjs/loader:1024:12)
2024-07-03 02:40:10.366 - error: backitup.1 (7099) [iobroker/iobroker] at cjsLoader (node:internal/modules/esm/translators:348:17)
2024-07-03 02:40:10.366 - error: backitup.1 (7099) [iobroker/iobroker] at ModuleWrap. (node:internal/modules/esm/translators:297:7)
2024-07-03 02:40:10.366 - error: backitup.1 (7099) [iobroker/iobroker] at ModuleJob.run (node:internal/modules/esm/module_job:222:25) {
2024-07-03 02:40:10.366 - error: backitup.1 (7099) [iobroker/iobroker] errno: -2,
2024-07-03 02:40:10.366 - error: backitup.1 (7099) [iobroker/iobroker] code: 'ENOENT',
2024-07-03 02:40:10.366 - error: backitup.1 (7099) [iobroker/iobroker] syscall: 'uv_cwd'
2024-07-03 02:40:10.366 - error: backitup.1 (7099) [iobroker/iobroker] }
2024-07-03 02:40:10.366 - error: backitup.1 (7099) [iobroker/iobroker] Node.js v20.15.0
2024-07-03 02:40:15.414 - error: backitup.1 (7099) [iobroker/onedrive] Onedrive: File "/opt/iobroker/backups/iobroker_2024_07_03-02_40_10_backupiobroker.tar.gz" not found
2024-07-03 02:40:16.955 - error: backitup.1 (7099) [iobroker/googledrive] Google Drive: File "/opt/iobroker/backups/iobroker_2024_07_03-02_40_10_backupiobroker.tar.gz" not found
2024-07-03 02:40:21.761 - error: backitup.1 (7099) [iobroker/clean] Backup files not deleted from /opt/iobroker/backups because some errors.

**Comment by simatec** [comment]
Please install the latest Github version.
I have included a try & catch there to localise the problem.

Basically uv_cwd is not a problem of Backitup, but a problem of node or your system. No working directory is found or cannot be accessed.

Please post the log if the backup was successful and also post the log if the error occurs again.

**Comment by walburgf** [comment]
I installed backitup now directly from github.
Now the backup is working again. So we have to wait until the issues happens again....

Here's the log of the working backup:

13:33:28.149INFOguiBackup gestartet ...
13:33:28.319DEBUGiobrokerCurrent working directory: /opt/iobroker/node_modules/iobroker.backitup
13:33:28.360DEBUGiobrokerioPath: /opt/iobroker/node_modules/iobroker.js-controller/iobroker.js
13:33:28.999DEBUGiobrokerhost.iobroker-pve 9933 states saved
13:33:29.151DEBUGiobrokerhost.iobroker-pve 11726 objects saved
13:33:29.743DEBUGiobrokerBackup created: /opt/iobroker/backups/iobroker_2024_07_03-13_33_29_backupiobroker.tar.gz
13:33:29.747DEBUGiobrokerThis backup can only be restored with js-controller version up from 4.1
13:33:30.759DEBUGiobrokerdone
13:33:32.588DEBUGjavascriptsCreated javascript_tmp directory: "/opt/iobroker/backups/tmpScripts"
13:33:34.219DEBUGjavascriptsfound Script: _Test
13:33:34.452DEBUGjavascriptsTry deleting the Javascript tmp directory: "/opt/iobroker/backups/tmpScripts"
13:33:34.493DEBUGjavascriptsJavascript tmp directory "/opt/iobroker/backups/tmpScripts" successfully deleted
13:33:34.497DEBUGjavascriptsBackup created: /opt/iobroker/backups/javascripts_2024_07_03-13_33_33_backupiobroker.tar.gz
13:33:34.500DEBUGjavascriptsdone
13:33:35.872DEBUGonedriveOnedrive: Copy iobroker_2024_07_03-13_33_29_backupiobroker.tar.gz...
13:33:36.327DEBUGonedrive21% uploaded from iobroker_2024_07_03-13_33_29_backupiobroker.tar.gz
13:33:36.573DEBUGonedrive41% uploaded from iobroker_2024_07_03-13_33_29_backupiobroker.tar.gz
13:33:36.846DEBUGonedrive62% uploaded from iobroker_2024_07_03-13_33_29_backupiobroker.tar.gz
13:33:37.127DEBUGonedrive82% uploaded from iobroker_2024_07_03-13_33_29_backupiobroker.tar.gz
13:33:37.423DEBUGonedrive100% uploaded from iobroker_2024_07_03-13_33_29_backupiobroker.tar.gz
13:33:37.429DEBUGonedriveiobroker_2024_07_03-13_33_29_backupiobroker.tar.gz with Id: 8F5D95BD4CB47FC!714368 saved on Onedrive
13:33:37.433DEBUGonedriveOnedrive: Copy javascripts_2024_07_03-13_33_33_backupiobroker.tar.gz...
13:33:37.753DEBUGonedrive100% uploaded from javascripts_2024_07_03-13_33_33_backupiobroker.tar.gz
13:33:37.756DEBUGonedrivejavascripts_2024_07_03-13_33_33_backupiobroker.tar.gz with Id: 8F5D95BD4CB47FC!714369 saved on Onedrive
13:33:37.761DEBUGonedrivedone
13:33:38.362DEBUGgoogledriveGoogle Drive: Copy iobroker_2024_07_03-13_33_29_backupiobroker.tar.gz...
13:33:42.584DEBUGgoogledriveGoogle Drive: Copy javascripts_2024_07_03-13_33_33_backupiobroker.tar.gz...
13:33:44.459DEBUGgoogledrivedone
13:33:44.609DEBUGcleanNo older backup files are deleted, because this backup was started manually
13:33:44.649DEBUGcleandone
13:33:44.761DEBUGhistoryHTMLnew history html values created
13:33:44.844DEBUGhistoryHTMLdone
13:33:44.997DEBUGhistoryJSONnew history json values created
13:33:45.038DEBUGhistoryJSONdone
13:33:47.503DEBUGnotificationdone
13:33:47.658INFOguiDas Backup wurde erfolgreich erstellt!

**Comment by walburgf** [comment]
backup now again show the following errors:

2024-07-04 08:53:48.079 - error: backitup.1 (8851) [iobroker/iobroker] node:internal/bootstrap/switches/does_own_process_state:144
2024-07-04 08:53:48.081 - error: backitup.1 (8851) [iobroker/iobroker] cachedCwd = rawMethods.cwd();
2024-07-04 08:53:48.081 - error: backitup.1 (8851) [iobroker/iobroker] ^
2024-07-04 08:53:48.081 - error: backitup.1 (8851) [iobroker/iobroker] Error: ENOENT: no such file or directory, uv_cwd
2024-07-04 08:53:48.081 - error: backitup.1 (8851) [iobroker/iobroker] at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:144:28)
2024-07-04 08:53:48.081 - error: backitup.1 (8851) [iobroker/iobroker] at process.cwd (/opt/iobroker/node_modules/graceful-fs/polyfills.js:10:19)
2024-07-04 08:53:48.081 - error: backitup.1 (8851) [iobroker/iobroker] at Object. (/opt/iobroker/node_modules/yargs/build/index.cjs:1:60970)
2024-07-04 08:53:48.081 - error: backitup.1 (8851) [iobroker/iobroker] at Module._compile (node:internal/modules/cjs/loader:1358:14)
2024-07-04 08:53:48.081 - error: backitup.1 (8851) [iobroker/iobroker] at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
2024-07-04 08:53:48.081 - error: backitup.1 (8851) [iobroker/iobroker] at Module.load (node:internal/modules/cjs/loader:1208:32)
2024-07-04 08:53:48.081 - error: backitup.1 (8851) [iobroker/iobroker] at Module._load (node:internal/modules/cjs/loader:1024:12)
2024-07-04 08:53:48.081 - error: backitup.1 (8851) [iobroker/iobroker] at cjsLoader (node:internal/modules/esm/translators:348:17)
2024-07-04 08:53:48.082 - error: backitup.1 (8851) [iobroker/iobroker] at ModuleWrap. (node:internal/modules/esm/translators:297:7)
2024-07-04 08:53:48.082 - error: backitup.1 (8851) [iobroker/iobroker] at ModuleJob.run (node:internal/modules/esm/module_job:222:25) {
2024-07-04 08:53:48.082 - error: backitup.1 (8851) [iobroker/iobroker] errno: -2,
2024-07-04 08:53:48.082 - error: backitup.1 (8851) [iobroker/iobroker] code: 'ENOENT',
2024-07-04 08:53:48.082 - error: backitup.1 (8851) [iobroker/iobroker] syscall: 'uv_cwd'
2024-07-04 08:53:48.082 - error: backitup.1 (8851) [iobroker/iobroker] }
2024-07-04 08:53:48.082 - error: backitup.1 (8851) [iobroker/iobroker] Node.js v20.15.0
2024-07-04 08:53:53.065 - error: backitup.1 (8851) [iobroker/onedrive] Onedrive: File "/opt/iobroker/backups/iobroker_2024_07_04-08_53_47_backupiobroker.tar.gz" not found
2024-07-04 08:53:54.089 - error: backitup.1 (8851) [iobroker/googledrive] Google Drive: File "/opt/iobroker/backups/iobroker_2024_07_04-08_53_47_backupiobroker.tar.gz" not found
2024-07-04 08:53:56.913 - error: backitup.1 (8851) [iobroker/clean] Backup files not deleted from /opt/iobroker/backups because some errors.

and in the backitup output:

08:56:37.284INFOguiBackup gestartet ...
08:56:37.448DEBUGiobrokerCurrent working directory: /opt/iobroker/node_modules/iobroker.backitup
08:56:37.490DEBUGiobrokerioPath: /opt/iobroker/node_modules/iobroker.js-controller/iobroker.js
08:56:37.670DEBUGiobrokerdone
08:56:39.451DEBUGjavascriptsCreated javascript_tmp directory: "/opt/iobroker/backups/tmpScripts"
08:56:41.074DEBUGjavascriptsfound Script: _Test
08:56:41.310DEBUGjavascriptsTry deleting the Javascript tmp directory: "/opt/iobroker/backups/tmpScripts"
08:56:41.352DEBUGjavascriptsJavascript tmp directory "/opt/iobroker/backups/tmpScripts" successfully deleted
08:56:41.355DEBUGjavascriptsdone
08:56:42.632ERRORonedriveOnedrive: File "/opt/iobroker/backups/iobroker_2024_07_04-08_56_38_backupiobroker.tar.gz" not found
08:56:42.636DEBUGonedriveOnedrive: Copy javascripts_2024_07_04-08_56_40_backupiobroker.tar.gz...
08:56:43.052DEBUGonedrive100% uploaded from javascripts_2024_07_04-08_56_40_backupiobroker.tar.gz
08:56:43.094DEBUGonedrivedone
08:56:43.670ERRORgoogledriveGoogle Drive: File "/opt/iobroker/backups/iobroker_2024_07_04-08_56_38_backupiobroker.tar.gz" not found
08:56:43.806DEBUGgoogledriveGoogle Drive: Copy javascripts_2024_07_04-08_56_40_backupiobroker.tar.gz...
08:56:46.205DEBUGgoogledrivedone
08:56:46.369ERRORcleanBackup files not deleted from /opt/iobroker/backups because some errors.
08:56:46.398DEBUGcleandone
08:56:46.507DEBUGhistoryHTMLnew history html values created
08:56:46.589DEBUGhistoryHTMLdone
08:56:46.741DEBUGhistoryJSONnew history json values created
08:56:46.783DEBUGhistoryJSONdone
08:56:49.243DEBUGnotificationAdmin notification will be sent
08:56:49.286DEBUGnotificationdone
08:56:49.394WARNguiDas Backup konnte nicht vollständig erstellt werden!

**Comment by simatec** [comment]
OK, we need to look deeper into your system. It's not a problem with Backitup, it's a problem with npm.

Please post the detailed output of `iob diag` here, then run an `iob fix` and then post the detailed output of `iob diag` again

Basically it should be noted that it is not a bug of Backitup. All paths are recognised correctly there

**Comment by walburgf** [comment]
iob diag showed errors in the node js installation:

*** NodeJS-Installation ***

/usr/bin/nodejs         v20.15.0
/usr/local/bin/node             v20.15.0
/usr/local/bin/npm              10.7.0
/usr/local/bin/npx              10.7.0
/usr/local/bin/corepack         0.28.1
*** nodejs is NOT correctly installed ***

nodejs:
  Installed: 20.15.0-1nodesource1
  Candidate: 20.15.0-1nodesource1
  Version table:
 *** 20.15.0-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
        100 /var/lib/dpkg/status
     20.14.0-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
     20.13.1-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
     20.13.0-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
     20.12.2-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
     20.12.1-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
     20.12.0-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
     20.11.1-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
     20.11.0-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
     20.10.0-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
     20.9.0-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
     20.8.1-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
     20.8.0-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
     20.7.0-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
     20.6.1-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
     20.6.0-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
     20.5.1-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
     20.5.0-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
     20.4.0-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
     20.3.1-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
     20.3.0-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
     20.2.0-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
     20.1.0-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
     20.0.0-1nodesource1 1001
        500 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages
     18.19.0+dfsg-6~deb12u2 500
        500 http://deb.debian.org/debian bookworm/main amd64 Packages
     18.19.0+dfsg-6~deb12u1 500
        500 http://security.debian.org bookworm-security/main amd64 Packages

Temp directories causing npm8 problem: 0
No problems detected

Errors in npm tree:

*** ioBroker-Installation ***

after running iob stop and iob fix the output was:

   Your installation was fixed successfully
    Run iobroker start to start ioBroker again!

Running iob diag again showed the same errors again.....

I also ran iob nodejs-update, but this did not resolve the issue....

Do you have any more ideas how to fix this?

**Comment by simatec** [comment]
Stop your iobroker and carry out the following steps

`````
iob stop
sudo apt remove nodejs 
sudo apt update && sudo apt upgrade -y
sudo apt install -y ca-certificates curl gnupg
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
NODE_MAJOR=20
echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
sudo apt update && sudo apt install nodejs -y
````
After this...

`````
iob fix
iob diag
iob restart
`````

Post the full Output from `iob diag`

**Comment by walburgf** [comment]
I followed your instructions, but the errors are still reported in the iob diag 
[iob_diag.log](https://github.com/user-attachments/files/16100178/iob_diag.log)

**Comment by simatec** [comment]
@Grothesk242 any ideas?

**Comment by Grothesk242** [comment]
Im Zweifel liegt's an nodejs: 

nodejs is NOT correctly installed

Und/oder an  priviledged/unpriviledged container.

**Comment by simatec** [comment]
I think the most sensible way would be to create a new machine and install iobroker as per the instructions, restore the backup and you're done. 

Something has gone wrong with your system.

**Comment by walburgf** [comment]
I made a fresh installation of iobroker and made a restore of the backup.
Now everything is running fine again and iob diag showed, that nodejs is installed correctly.

Thank you for your support.

I will close the issue and reopen it, if the error is happening again... :-)
