### ISSUE TITLE
Error while updating to 1.3.1 in compact mode

### ISSUE THREAD

**Issue by cburghardt** [simatec/ioBroker.backitup#205]
backitup is running in compact mode in my setup.
During the update to 1.3.1 an error occurred and the start failed

```
2019-12-03 17:27:58.370  - ^[[32minfo^[[39m: host.iobroker1 iobroker Update backitup from @1.3.0 to @1.3.1
2019-12-03 17:27:58.389  - ^[[32minfo^[[39m: host.iobroker1 iobroker host.iobroker1 Adapter "system.adapter.backitup.0" is stopped.
2019-12-03 17:27:58.421  - ^[[32minfo^[[39m: host.iobroker1.compactgroup1 "system.adapter.backitup.0" disabled
2019-12-03 17:27:58.427  - ^[[32minfo^[[39m: host.iobroker1.compactgroup1 stopInstance system.adapter.backitup.0 (force=false, process=true)
2019-12-03 17:27:58.441  - ^[[32minfo^[[39m: host.iobroker1 "system.adapter.backitup.0" disabled
2019-12-03 17:27:58.442  - ^[[32minfo^[[39m: host.iobroker1 stopInstance system.adapter.backitup.0 (force=false, process=true)
2019-12-03 17:27:58.450  - ^[[32minfo^[[39m: backitup.0 (COMPACT) Got terminate signal TERMINATE_YOURSELF
2019-12-03 17:27:58.487  - ^[[32minfo^[[39m: host.iobroker1.compactgroup1 stopInstance system.adapter.backitup.0 send kill signal
2019-12-03 17:27:58.953  - ^[[32minfo^[[39m: backitup.0 (COMPACT) terminating
2019-12-03 17:27:58.955  - ^[[32minfo^[[39m: backitup.0 (COMPACT) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
2019-12-03 17:27:59.057  - ^[[32minfo^[[39m: host.iobroker1 iobroker NPM version: 6.4.1npm install iobroker.backitup@1.3.1 --loglevel error --prefix "/opt/iobroker" (System call)
2019-12-03 17:27:59.490  - ^[[32minfo^[[39m: host.iobroker1.compactgroup1 stopInstance system.adapter.backitup.0 killing pid undefined
2019-12-03 17:27:59.539  - ^[[32minfo^[[39m: host.iobroker1.compactgroup1 instance system.adapter.backitup.0 terminated with code -100 (START_IMMEDIATELY_AFTER_STOP)
2019-12-03 17:27:59.955  - ^[[32minfo^[[39m: backitup.0 (COMPACT) terminating with timeout
2019-12-03 17:28:39.170  - ^[[32minfo^[[39m: host.iobroker1 iobroker upload [3] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/words.js words.js application/javascript
2019-12-03 17:28:39.231  - ^[[32minfo^[[39m: host.iobroker1 iobroker Update "system.adapter.backitup.0"
2019-12-03 17:28:39.482  - ^[[32minfo^[[39m: host.iobroker1 iobroker upload [2] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/index_m.html index_m.html text/html
2019-12-03 17:28:39.540  - ^[[32minfo^[[39m: host.iobroker1 iobroker upload [1] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/index.html index.html text/html
2019-12-03 17:28:39.596  - ^[[32minfo^[[39m: host.iobroker1 iobroker upload [0] backitup.admin /opt/iobroker/node_modules/iobroker.backitup/admin/backitup.png backitup.png image/png
2019-12-03 17:28:39.654  - ^[[32minfo^[[39m: host.iobroker1 iobroker Adapter "backitup" updated
2019-12-03 17:28:39.655  - ^[[32minfo^[[39m: host.iobroker1 iobroker host.iobroker1 Adapter "system.adapter.backitup.0" is started
2019-12-03 17:28:39.685  - ^[[32minfo^[[39m: host.iobroker1.compactgroup1 "system.adapter.backitup.0" enabled
2019-12-03 17:28:39.705  - ^[[32minfo^[[39m: host.iobroker1 "system.adapter.backitup.0" enabled
2019-12-03 17:28:39.707  - ^[[32minfo^[[39m: host.iobroker1 instance system.adapter.backitup.0 is handled by compact group controller pid 5027
2019-12-03 17:28:39.705  - ^[[32minfo^[[39m: host.iobroker1 "system.adapter.backitup.0" enabled
2019-12-03 17:28:39.707  - ^[[32minfo^[[39m: host.iobroker1 instance system.adapter.backitup.0 is handled by compact group controller pid 5027
2019-12-03 17:28:40.420  - ^[[31merror^[[39m: host.iobroker1.compactgroup1 Cannot start backitup.0 in compact mode. Fallback to normal start! : ENOENT: no such file or directory, open '/opt/iobroker/node_modules/gtoken/node_modules/mime/index.js'
2019-12-03 17:28:40.420  - ^[[31merror^[[39m: undefined
2019-12-03 17:28:40.433  - ^[[32minfo^[[39m: host.iobroker1.compactgroup1 instance system.adapter.backitup.0 started with pid 20147
2019-12-03 17:28:40.717  - ^[[32minfo^[[39m: host.iobroker1 iobroker exit 0
2019-12-03 17:28:44.734  - ^[[32minfo^[[39m: backitup.0 (20147) starting. Version 1.3.1 in /opt/iobroker/node_modules/iobroker.backitup, node: v8.16.1
2019-12-03 17:28:44.800  - ^[[32minfo^[[39m: backitup.0 (20147) [iobroker] backup was activated at 02:00 every 1 day(s)
2019-12-03 17:28:44.916  - ^[[31merror^[[39m: backitup.0 (20147) uncaught exception: Cannot read property 'val' of null
2019-12-03 17:28:44.916  - ^[[31merror^[[39m: backitup.0 (20147) TypeError: Cannot read property 'val' of null
    at Adapter.adapter.on (/opt/iobroker/node_modules/iobroker.backitup/main.js:58:20)
    at emitTwo (events.js:126:13)
    at Adapter.emit (events.js:214:7)
    at Immediate.setImmediate [as _onImmediate] (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4748:38)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
2019-12-03 17:28:44.922  - ^[[31merror^[[39m: backitup.0 (20147) uncaught exception: Cannot read property 'val' of null
2019-12-03 17:28:44.923  - ^[[31merror^[[39m: backitup.0 (20147) TypeError: Cannot read property 'val' of null
    at Adapter.adapter.on (/opt/iobroker/node_modules/iobroker.backitup/main.js:58:20)
    at emitTwo (events.js:126:13)
    at Adapter.emit (events.js:214:7)
    at Immediate.setImmediate [as _onImmediate] (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4748:38)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
2019-12-03 17:28:45.425  - ^[[32minfo^[[39m: backitup.0 (20147) terminating
2019-12-03 17:28:45.427  - ^[[32minfo^[[39m: backitup.0 (20147) Terminated (NO_ERROR): Without reason
2019-12-03 17:28:46.010  - ^[[31merror^[[39m: host.iobroker1.compactgroup1 Caught by controller[0]: TypeError: Cannot read property 'val' of null
2019-12-03 17:28:46.010  - ^[[31merror^[[39m: host.iobroker1.compactgroup1 Caught by controller[0]:     at Adapter.adapter.on (/opt/iobroker/node_modules/iobroker.backitup/main.js:58:20)
2019-12-03 17:28:46.011  - ^[[31merror^[[39m: host.iobroker1.compactgroup1 Caught by controller[0]:     at emitTwo (events.js:126:13)
2019-12-03 17:28:46.011  - ^[[31merror^[[39m: host.iobroker1.compactgroup1 Caught by controller[0]:     at Adapter.emit (events.js:214:7)
2019-12-03 17:28:46.011  - ^[[31merror^[[39m: host.iobroker1.compactgroup1 Caught by controller[0]:     at Immediate.setImmediate [as _onImmediate] (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4748:38)
2019-12-03 17:28:46.011  - ^[[31merror^[[39m: host.iobroker1.compactgroup1 Caught by controller[0]:     at runCallback (timers.js:810:20)
2019-12-03 17:28:46.012  - ^[[31merror^[[39m: host.iobroker1.compactgroup1 Caught by controller[0]:     at tryOnImmediate (timers.js:768:5)
2019-12-03 17:28:46.012  - ^[[31merror^[[39m: host.iobroker1.compactgroup1 Caught by controller[0]:     at processImmediate [as _immediateCallback] (timers.js:745:5)
2019-12-03 17:28:46.014  - ^[[31merror^[[39m: host.iobroker1.compactgroup1 Caught by controller[1]: TypeError: Cannot read property 'val' of null
2019-12-03 17:28:46.014  - ^[[31merror^[[39m: host.iobroker1.compactgroup1 Caught by controller[1]:     at Adapter.adapter.on (/opt/iobroker/node_modules/iobroker.backitup/main.js:58:20)
2019-12-03 17:28:46.014  - ^[[31merror^[[39m: host.iobroker1.compactgroup1 Caught by controller[1]:     at emitTwo (events.js:126:13)
2019-12-03 17:28:46.015  - ^[[31merror^[[39m: host.iobroker1.compactgroup1 Caught by controller[1]:     at Adapter.emit (events.js:214:7)
2019-12-03 17:28:46.015  - ^[[31merror^[[39m: host.iobroker1.compactgroup1 Caught by controller[1]:     at Immediate.setImmediate [as _onImmediate] (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4748:38)
2019-12-03 17:28:46.015  - ^[[31merror^[[39m: host.iobroker1.compactgroup1 Caught by controller[1]:     at runCallback (timers.js:810:20)
2019-12-03 17:28:46.016  - ^[[31merror^[[39m: host.iobroker1.compactgroup1 Caught by controller[1]:     at tryOnImmediate (timers.js:768:5)
2019-12-03 17:28:46.016  - ^[[31merror^[[39m: host.iobroker1.compactgroup1 Caught by controller[1]:     at processImmediate [as _immediateCallback] (timers.js:745:5)
2019-12-03 17:28:46.016  - ^[[32minfo^[[39m: host.iobroker1.compactgroup1 instance system.adapter.backitup.0 terminated with code 0 (NO_ERROR)
2019-12-03 17:28:46.016  - ^[[32minfo^[[39m: host.iobroker1.compactgroup1 Restart adapter system.adapter.backitup.0 because enabled
2019-12-03 17:29:16.027  - ^[[31merror^[[39m: host.iobroker1.compactgroup1 Cannot start backitup.0 in compact mode. Fallback to normal start! : ENOENT: no such file or directory, open '/opt/iobroker/node_modules/gtoken/node_modules/mime/index.js'
2019-12-03 17:29:16.028  - ^[[31merror^[[39m: undefined
2019-12-03 17:29:16.042  - ^[[32minfo^[[39m: host.iobroker1.compactgroup1 instance system.adapter.backitup.0 started with pid 20161
2019-12-03 17:29:20.084  - ^[[32minfo^[[39m: backitup.0 (20161) starting. Version 1.3.1 in /opt/iobroker/node_modules/iobroker.backitup, node: v8.16.1
2019-12-03 17:29:20.144  - ^[[32minfo^[[39m: backitup.0 (20161) [iobroker] backup was activated at 02:00 every 1 day(s)
2019-12-03 17:30:15.383  - ^[[32minfo^[[39m: host.iobroker1.compactgroup1 "system.adapter.backitup.0" disabled
2019-12-03 17:30:15.383  - ^[[32minfo^[[39m: host.iobroker1.compactgroup1 stopInstance system.adapter.backitup.0 (force=false, process=true)
2019-12-03 17:30:15.402  - ^[[32minfo^[[39m: host.iobroker1 "system.adapter.backitup.0" disabled
2019-12-03 17:30:15.403  - ^[[32minfo^[[39m: host.iobroker1 stopInstance system.adapter.backitup.0 (force=false, process=true)
2019-12-03 17:30:15.410  - ^[[32minfo^[[39m: host.iobroker1.compactgroup1 stopInstance system.adapter.backitup.0 send kill signal
2019-12-03 17:30:15.410  - ^[[32minfo^[[39m: backitup.0 (20161) Got terminate signal TERMINATE_YOURSELF
2019-12-03 17:30:15.913  - ^[[32minfo^[[39m: backitup.0 (20161) terminating
2019-12-03 17:30:15.914  - ^[[32minfo^[[39m: backitup.0 (20161) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
2019-12-03 17:30:16.413  - ^[[32minfo^[[39m: host.iobroker1.compactgroup1 stopInstance system.adapter.backitup.0 killing pid 20161
2019-12-03 17:30:16.493  - ^[[32minfo^[[39m: host.iobroker1.compactgroup1 instance system.adapter.backitup.0 terminated with code 156 (156)
2019-12-03 17:30:22.893  - ^[[32minfo^[[39m: host.iobroker1.compactgroup1 "system.adapter.backitup.0" enabled
2019-12-03 17:30:22.908  - ^[[32minfo^[[39m: host.iobroker1 "system.adapter.backitup.0" enabled
2019-12-03 17:30:22.911  - ^[[32minfo^[[39m: host.iobroker1 instance system.adapter.backitup.0 is handled by compact group controller pid 5027
2019-12-03 17:30:22.905  - ^[[31merror^[[39m: host.iobroker1.compactgroup1 Cannot start backitup.0 in compact mode. Fallback to normal start! : ENOENT: no such file or directory, open '/opt/iobroker/node_modules/gtoken/node_modules/mime/index.js'
2019-12-03 17:30:22.906  - ^[[31merror^[[39m: undefined
2019-12-03 17:30:22.920  - ^[[32minfo^[[39m: host.iobroker1.compactgroup1 instance system.adapter.backitup.0 started with pid 20177
2019-12-03 17:30:26.887  - ^[[32minfo^[[39m: backitup.0 (20177) starting. Version 1.3.1 in /opt/iobroker/node_modules/iobroker.backitup, node: v8.16.1
2019-12-03 17:30:26.950  - ^[[32minfo^[[39m: backitup.0 (20177) [iobroker] backup was activated at 02:00 every 1 day(s)
```

**Comment by simatec** [comment]
Fixed ...

**Comment by cburghardt** [comment]
Aktuelle Version, gleiches Problem:

host.iobroker1 | 2019-12-17 02:00:22.108 | error | Caught by controller[3]: at processImmediate [as _immediateCallback] (timers.js:745:5)
-- | -- | -- | --
host.iobroker1 | 2019-12-17 02:00:22.108 | error | Caught by controller[3]: at tryOnImmediate (timers.js:768:5)
host.iobroker1 | 2019-12-17 02:00:22.108 | error | Caught by controller[3]: at runCallback (timers.js:819:39)
host.iobroker1 | 2019-12-17 02:00:22.108 | error | Caught by controller[3]: at Immediate.executeScripts [as _onImmediate] (/opt/iobroker/node_modules/iobroker.backitup/lib/execute.js:216:22)
host.iobroker1 | 2019-12-17 02:00:22.107 | error | Caught by controller[3]: at Object.command (/opt/iobroker/node_modules/iobroker.backitup/lib/scripts/92-history.js:10:25)
host.iobroker1 | 2019-12-17 02:00:22.107 | error | Caught by controller[3]: at Adapter.getState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5407:29)
host.iobroker1 | 2019-12-17 02:00:22.107 | error | Caught by controller[3]: at options.adapter.getState (/opt/iobroker/node_modules/iobroker.backitup/lib/scripts/92-history.js:11:37)
host.iobroker1 | 2019-12-17 02:00:22.107 | error | Caught by controller[3]: TypeError: Cannot read property 'val' of undefined
host.iobroker1 | 2019-12-17 02:00:22.107 | error | Caught by controller[2]: at processImmediate [as _immediateCallback] (timers.js:745:5)
host.iobroker1 | 2019-12-17 02:00:22.107 | error | Caught by controller[2]: at tryOnImmediate (timers.js:768:5)
host.iobroker1 | 2019-12-17 02:00:22.107 | error | Caught by controller[2]: at runCallback (timers.js:819:39)
host.iobroker1 | 2019-12-17 02:00:22.106 | error | Caught by controller[2]: at Immediate.executeScripts [as _onImmediate] (/opt/iobroker/node_modules/iobroker.backitup/lib/execute.js:216:22)
host.iobroker1 | 2019-12-17 02:00:22.106 | error | Caught by controller[2]: at Object.command (/opt/iobroker/node_modules/iobroker.backitup/lib/scripts/92-history.js:10:25)
host.iobroker1 | 2019-12-17 02:00:22.106 | error | Caught by controller[2]: at Adapter.getState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5407:29)
host.iobroker1 | 2019-12-17 02:00:22.106 | error | Caught by controller[2]: at options.adapter.getState (/opt/iobroker/node_modules/iobroker.backitup/lib/scripts/92-history.js:11:37)
host.iobroker1 | 2019-12-17 02:00:22.106 | error | Caught by controller[2]: TypeError: Cannot read property 'val' of undefined
host.iobroker1 | 2019-12-17 02:00:22.106 | error | Caught by controller[1]: at processImmediate [as _immediateCallback] (timers.js:745:5)
host.iobroker1 | 2019-12-17 02:00:22.105 | error | Caught by controller[1]: at tryOnImmediate (timers.js:768:5)
host.iobroker1 | 2019-12-17 02:00:22.105 | error | Caught by controller[1]: at runCallback (timers.js:819:39)
host.iobroker1 | 2019-12-17 02:00:22.105 | error | Caught by controller[1]: at Immediate.executeScripts [as _onImmediate] (/opt/iobroker/node_modules/iobroker.backitup/lib/execute.js:216:22)
host.iobroker1 | 2019-12-17 02:00:22.105 | error | Caught by controller[1]: at Object.command (/opt/iobroker/node_modules/iobroker.backitup/lib/scripts/92-history.js:10:25)
host.iobroker1 | 2019-12-17 02:00:22.105 | error | Caught by controller[1]: at Adapter.getState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5407:29)
host.iobroker1 | 2019-12-17 02:00:22.105 | error | Caught by controller[1]: at options.adapter.getState (/opt/iobroker/node_modules/iobroker.backitup/lib/scripts/92-history.js:11:37)
host.iobroker1 | 2019-12-17 02:00:22.105 | error | Caught by controller[1]: TypeError: Cannot read property 'val' of undefined
host.iobroker1 | 2019-12-17 02:00:22.104 | error | Caught by controller[0]: at processImmediate [as _immediateCallback] (timers.js:745:5)
host.iobroker1 | 2019-12-17 02:00:22.104 | error | Caught by controller[0]: at tryOnImmediate (timers.js:768:5)
host.iobroker1 | 2019-12-17 02:00:22.104 | error | Caught by controller[0]: at runCallback (timers.js:819:39)
host.iobroker1 | 2019-12-17 02:00:22.104 | error | Caught by controller[0]: at Immediate.executeScripts [as _onImmediate] (/opt/iobroker/node_modules/iobroker.backitup/lib/execute.js:216:22)
host.iobroker1 | 2019-12-17 02:00:22.104 | error | Caught by controller[0]: at Object.command (/opt/iobroker/node_modules/iobroker.backitup/lib/scripts/92-history.js:10:25)
host.iobroker1 | 2019-12-17 02:00:22.104 | error | Caught by controller[0]: at Adapter.getState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5407:29)
host.iobroker1 | 2019-12-17 02:00:22.103 | error | Caught by controller[0]: at options.adapter.getState (/opt/iobroker/node_modules/iobroker.backitup/lib/scripts/92-history.js:11:37)
host.iobroker1 | 2019-12-17 02:00:22.103 | error | Caught by controller[0]: TypeError: Cannot read property 'val' of undefined

**Comment by simatec** [comment]
Das ist nicht das gleiche Problem, aber jetzt auch gefixt.
