### ISSUE TITLE
Adapter is not starting after iobroker update js-contr. from 1.5.4 to 2.2.8

### ISSUE THREAD

**Issue by flyandromeda** [simatec/ioBroker.backitup#241]
Hi!
After iobroker system upgrade from js-controller 1.5.4 to 2.2.8 the backitup adapter is not able to start.

System: 
-Raspi3B+
-js-controller 2.2.8
-Node.js: v10.18.1
-NPM: v6.13.4

I´ve tried several things:
- remove and re-install the adapter via npm in several older versions.
- raspbi system is up to date.

the log:

host.raspberrypi | 2020-02-06 12:00:53.349 | info | "system.adapter.backitup.0" disabled
-- | -- | -- | --
host.raspberrypi | 2020-02-06 12:00:47.399 | info | Restart adapter system.adapter.backitup.0 because enabled
host.raspberrypi | 2020-02-06 12:00:47.399 | error | instance system.adapter.backitup.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.raspberrypi | 2020-02-06 12:00:47.398 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.raspberrypi | 2020-02-06 12:00:47.398 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:778:30)
host.raspberrypi | 2020-02-06 12:00:47.398 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/gaxios/build/src/gaxios.js:21:37)
host.raspberrypi | 2020-02-06 12:00:47.398 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:25:18)
host.raspberrypi | 2020-02-06 12:00:47.397 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:692:17)
host.raspberrypi | 2020-02-06 12:00:47.397 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.raspberrypi | 2020-02-06 12:00:47.397 | error | Caught by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.raspberrypi | 2020-02-06 12:00:47.397 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
host.raspberrypi | 2020-02-06 12:00:47.396 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.raspberrypi | 2020-02-06 12:00:47.396 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:723:23)
host.raspberrypi | 2020-02-06 12:00:47.396 | error | Caught by controller[0]: SyntaxError: Invalid or unexpected token
host.raspberrypi | 2020-02-06 12:00:47.395 | error | Caught by controller[0]: ^
host.raspberrypi | 2020-02-06 12:00:47.395 | error | Caught by controller[0]: �PNG
host.raspberrypi | 2020-02-06 12:00:47.393 | error | Caught by controller[0]: /opt/iobroker/node_modules/gaxios/node_modules/is-stream/index.js:1
host.raspberrypi | 2020-02-06 12:00:45.630 | info | instance system.adapter.backitup.0 started with pid 1840

thanks for your help!
regards, Andy

**Comment by flyandromeda** [comment]
Problem no longer exists.
I de-installed first the instance, then the adapter.
After re-installing the adapter everthing is running.
