### ISSUE TITLE
Backup auf NAS funktioniert, jedoch kein Restore

### ISSUE THREAD

**Issue by guergen1** [simatec/ioBroker.backitup#277]
Der Adapter macht täglich eine Sicherung auf mein NAS, alle Dateien liegen brav dort.
Benötigte grade ein Restore von heute Nacht, die Dateien hat er auch brav angezeigt, jedoch beim restore meint der Adapter: File not found (odr so ähnlich)
Habe es dann zu Fuss in das Backup-Verzeichnis kopiert, dann hat er es auch genommen.
Der Adapter scheint für das restore das NAS nicht zu mounten.

**Comment by simatec** [comment]
Eventuell braucht dein NAS zu lange um zu antworten. Muss ich mir mal anschauen. 
Was sagt der Log?

**Comment by simatec** [comment]
Grundsätzlich gibt es aber ein HowTo zum Restore, indem auch eindeutig darauf hingewiesen wird, dass die beste und sicherste Variante ein Restore vom lokalen Pfad ist.

**Comment by guergen1** [comment]
Das Nas war ja online!
Die gesamten Backup´s hat er ja auch gesehen, aber wahrscheinlich speichert der Adapter die Daten

Was mir eben auch noch aufgefallen ist: Das Log zum Restore bleibt immer oben stehen, ein scrollen wird während des restores nicht möglich. Erst nach Exit (0) kann man wieder scrollen

Hier das Log:
`

2020-04-09 18:12:47.810  - warn:  backitup.0 (3128) States system pmessage  io.messagebox.system.adapter.backitup.0  {"command":"list","message":"cifs","from":"system.adapter.admin.0","callback":{"message":"cifs","id":626,"ack":false,"time":1586448767809},"_id":28103464}  Cannot read property 'type' of null
--
2020-04-09 18:12:47.815  - warn: backitup.0 (3128) TypeError: Cannot read property 'type' of null
at module.exports (/opt/iobroker/node_modules/iobroker.backitup/lib/list.js:22:40)
at Adapter.adapter.on.obj (/opt/iobroker/node_modules/iobroker.backitup/main.js:118:21)
at Adapter.emit (events.js:198:13)
at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4808:34)
at Immediate.setImmediate [as _onImmediate]  (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:227:41)
at runCallback (timers.js:705:18)
at tryOnImmediate (timers.js:676:5)
at processImmediate (timers.js:658:5)

`
`2020-04-09 18:16:09.043 - error: backitup.0 (28606) umount: /opt/iobroker/backups: not mounted.`

**Comment by simatec** [comment]
Wenn die Backups von NAS im Restore Tab gelesen und angezeigt werden, dann hat bereits ein mount stattgefunden. Nach 10 Minuten findet bei keiner weiteren Nutzung dann automatisch ein umount.

**Comment by guergen1** [comment]
Habe direkt nach dem auslesen das Restore gestartet
