### ISSUE TITLE
Adapter doesn't start after upgrade from version 1.4.5 to version 1.5.8

### ISSUE THREAD

**Issue by RainerMo** [simatec/ioBroker.backitup#316]
Hi Backitup team,

after upgrading my iobroker installation on a raspberry pi 4 the backupit adapter doesn't come up again.
Here's the errors from the log:

2020-06-30 11:48:58.751 - error: host.ioBroker-RasPi4 Caught by controller[0]: /opt/iobroker/node_modules/googleapis-common/node_modules/uuid/dist/esm-browser/index.js:1
2020-06-30 11:48:58.752 - error: host.ioBroker-RasPi4 Caught by controller[0]: export { default as v1 } from './v1.js';
2020-06-30 11:48:58.752 - error: host.ioBroker-RasPi4 Caught by controller[0]: ^^^^^^
2020-06-30 11:48:58.752 - error: host.ioBroker-RasPi4 Caught by controller[0]: SyntaxError: Unexpected token 'export'
2020-06-30 11:48:58.752 - error: host.ioBroker-RasPi4 Caught by controller[0]: at wrapSafe (internal/modules/cjs/loader.js:1060:16)
2020-06-30 11:48:58.752 - error: host.ioBroker-RasPi4 Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1108:27)
2020-06-30 11:48:58.753 - error: host.ioBroker-RasPi4 Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
2020-06-30 11:48:58.753 - error: host.ioBroker-RasPi4 Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:993:32)
2020-06-30 11:48:58.753 - error: host.ioBroker-RasPi4 Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:892:14)
2020-06-30 11:48:58.753 - error: host.ioBroker-RasPi4 Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:1033:19)
2020-06-30 11:48:58.754 - error: host.ioBroker-RasPi4 Caught by controller[0]: at require (internal/modules/cjs/helpers.js:72:18)
2020-06-30 11:48:58.754 - error: host.ioBroker-RasPi4 Caught by controller[0]: at Object. (/opt/iobroker/node_modules/googleapis-common/build/src/apirequest.js:20:14)
2020-06-30 11:48:58.754 - error: host.ioBroker-RasPi4 Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1144:30)
2020-06-30 11:48:58.754 - error: host.ioBroker-RasPi4 Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
2020-06-30 11:48:58.755 - error: host.ioBroker-RasPi4 instance system.adapter.backitup.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2020-06-30 11:48:58.755 - info: host.ioBroker-RasPi4 Restart adapter system.adapter.backitup.0 because enabled

Raspberry is running these module versions:
Node.js: v13.6.0
NPM: 6.13.4

What to do?
KR Rainer

**Comment by simatec** [comment]
Odd node versions are not supported.
Please update to node 14 or downgrade to node 12, which would be the current system for iobroker

**Comment by RainerMo** [comment]
Upgraded to node 14 - works so far!
Thank you for the quick support.
KR
