### ISSUE TITLE
Wiederherstellung klappt nicht

### ISSUE THREAD

**Issue by Elmo127** [simatec/ioBroker.backitup#372]
Hallo,

ich habe versucht meinen iobroker aus einem backup wieder neu aufzusetzen, da dieser abgeraucht ist.
Leider bekomme ich folgende Fehlermeldungen, welche dann auch die Wiederherstellung verhindern. Ich habe schon viele Beiträge gelesen und etliche Versionen von Adapter, Node, usw. installiert aber nichts hat geholfen.

Hier der Auszug aus dem Log:
2020-12-15 18:39:10.110 - error: backitup.0 (10011) [ERROR] [iobroker] [Not critical] Cannot delete object 0_userdata.0: "Object is marked as non deletable"
2020-12-15 18:39:10.111 - error: backitup.0 (10011) [ERROR] [iobroker] [Not critical] Cannot delete object alias.0: "Object is marked as non deletable"
2020-12-15 18:39:10.112 - error: backitup.0 (10011) [ERROR] [iobroker] [Not critical] Cannot delete object system.repositories: "Object is marked as non deletable"
2020-12-15 18:39:10.112 - error: backitup.0 (10011) [ERROR] [iobroker] [Not critical] Cannot delete object system.config: "Object is marked as non deletable"
2020-12-15 18:39:10.113 - error: backitup.0 (10011) [ERROR] [iobroker] [Not critical] Cannot delete object enum.functions: "Object is marked as non deletable"
2020-12-15 18:39:10.114 - error: backitup.0 (10011) [ERROR] [iobroker] [Not critical] Cannot delete object enum.rooms: "Object is marked as non deletable"
2020-12-15 18:39:10.158 - error: backitup.0 (10011) [ERROR] [iobroker] /opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemFileDB.js:243
2020-12-15 18:39:10.159 - error: backitup.0 (10011) [ERROR] [iobroker] delete this.dataset[id].acl.file;
2020-12-15 18:39:10.160 - error: backitup.0 (10011) [ERROR] [iobroker] ^
2020-12-15 18:39:10.160 - error: backitup.0 (10011) [ERROR] [iobroker] TypeError: Cannot convert undefined or null to object
2020-12-15 18:39:10.161 - error: backitup.0 (10011) [ERROR] [iobroker] at ObjectsInMemoryServer.setDefaultAcl (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemFileDB.js:243:41)
2020-12-15 18:39:10.162 - error: backitup.0 (10011) [ERROR] [iobroker] at ObjectsInMemoryServer._setObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemFileDB.js:1862:25)
2020-12-15 18:39:10.163 - error: backitup.0 (10011) [ERROR] [iobroker] at /opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemFileDB.js:2023:29
2020-12-15 18:39:10.163 - error: backitup.0 (10011) [ERROR] [iobroker] at Object.checkObjectRights (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsUtils.js:581:16)
2020-12-15 18:39:10.164 - error: backitup.0 (10011) [ERROR] [iobroker] at ObjectsInMemoryServer.setObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemFileDB.js:2019:15)
2020-12-15 18:39:10.165 - error: backitup.0 (10011) [ERROR] [iobroker] at BackupRestore._setObjHelper (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupBackup.js:427:22)
2020-12-15 18:39:10.165 - error: backitup.0 (10011) [ERROR] [iobroker] at processImmediate (internal/timers.js:463:21)
2020-12-15 18:39:10.168 - warn: backitup.0 (10011) Cannot read log file: ReferenceError: config is not defined

was könnte ich hier noch versuchen?

Danke und Gruß

**Comment by simatec** [comment]
Versuche es mal mit der Konsole. 
`iobroker restore <backupname>`

**Comment by Elmo127** [comment]
Hallo,

danke für die schnell Rückmeldung. Bekomme genau die selben Fehlermeldungen wie oben:

/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemFileDB.js:243
                delete this.dataset[id].acl.file;
                                        ^

TypeError: Cannot convert undefined or null to object
    at ObjectsInMemoryServer.setDefaultAcl (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemFileDB.js:243:41)
    at ObjectsInMemoryServer._setObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemFileDB.js:1862:25)
    at /opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemFileDB.js:2023:29
    at Object.checkObjectRights (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsUtils.js:581:16)
    at ObjectsInMemoryServer.setObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemFileDB.js:2019:15)
    at BackupRestore._setObjHelper (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupBackup.js:427:22)
    at processImmediate (internal/timers.js:463:21)

**Comment by simatec** [comment]
Dann ist dein System defekt. Versuche mal „iobroker fix“ 
Sollte das nicht helfen, setze am besten alles neu auf

**Comment by Elmo127** [comment]
habs gerade versucht. bringt leider auch nichts ... ich habs heute schon paar mal neu aufgesetzt. Das Backup scheint wenn ich durchschaue eigentlich auch gut aus. Also sofern ich das als Neuling beurteilen kann. Ich werde es morgen mal mit einer neue SD-Karte versuchen und Rückmeldung geben. Danke

**Comment by simatec** [comment]
Nach welche Anleitung hast du iobroker installiert?

**Comment by Elmo127** [comment]
zuerst mit einem kompletten image von https://www.iobroker.net/#de/download und dann "zu Fuß" mit folgenden beiden Videos aus Youtube:
- https://www.youtube.com/watch?v=Dev1qvhp0vM&t=330s
- https://www.youtube.com/watch?v=8W5w1RLU174&t=318s

Habe dann beide Male mit den Versionen herumgespielt und alles ausprobiert ...

**Comment by simatec** [comment]
Nimm bitte die offizielle Variante aus der iobroker Doku. Alles andere kann leider nicht supportet werden

**Comment by Elmo127** [comment]
Hallo,

habe es mittlerweile hinbekommen. Habe das System nochmal strikt nach der Doku aufgesetzt dann ging es. Ein paar Adapter haben gesponnen ansonsten läuft jetzt alles. Danke für Unterstützung. Denke der Issue kann geschlossen werden :)
