### ISSUE TITLE
Fehler bei Jarvis Backup

### ISSUE THREAD

**Issue by MarkSau** [simatec/ioBroker.backitup#388]
**Describe the bug**  
Added  Jarvis to BackupIt and started first Backup.
Error in Log. Backup aborted.

**Screenshots & Logfiles**  
`
--
2021-01-11 15:55:31.865 - error: backitup.0 (15608) uncaught exception: Cannot read property 'length' of undefined
2021-01-11 15:55:31.870 - error: backitup.0 (15608) TypeError: Cannot read property 'length' of undefined
at /opt/iobroker/node_modules/iobroker.backitup/lib/scripts/38-jarvis.js:12:32
at FSReqCallback.oncomplete (fs.js:171:23)
2021-01-11 15:55:31.871 - info: backitup.0 (15608) cleaned everything up...
2021-01-11 15:55:31.886 - info: backitup.0 (15608) terminating
2021-01-11 15:55:31.892 - info: backitup.0 (15608) Terminated (NO_ERROR): Without reason
2021-01-11 15:55:32.254 - error: host.MSNUC-IOB Caught by controller[0]: TypeError: Cannot read property 'length' of undefined
2021-01-11 15:55:32.254 - error: host.MSNUC-IOB Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.backitup/lib/scripts/38-jarvis.js:12:32
2021-01-11 15:55:32.255 - error: host.MSNUC-IOB Caught by controller[0]: at FSReqCallback.oncomplete (fs.js:171:23)
2021-01-11 15:55:32.255 - error: host.MSNUC-IOB instance system.adapter.backitup.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2021-01-11 15:55:32.256 - info: host.MSNUC-IOB Restart adapter system.adapter.backitup.0 because enabled
`

**Versions:**  
 - Adapter version: 1.8.4
 - JS-Controller version: 3.1.6
 - Node version:  v14.15.4
 - Operating system: Ubuntu 20.04.1 LTS

**Comment by simatec** [comment]
Das Backup ist erst ab Jarvis 2.2.0 möglich. 
Wenn du die Funktion nutzen möchtest, musst du die aktuelle Github Version von Jarvis installieren, da die 2.2.0 noch nicht im latest ist.

**Comment by simatec** [comment]
Ich habe die Fehlermeldung in Version 1.8.5 abgefangen und im Log gibt es einen Hinweis zur Jarvis Version
