### ISSUE TITLE
Redis Backup funktioniert nicht, wenn AOF aktiviert ist

### ISSUE THREAD

**Issue by Scrounger** [simatec/ioBroker.backitup#426]
neues Ticket da ich #301 nicht wieder öffnen kann.

@simatec 
> Grundsätzlich habe ich gelesen, dass AOF Aktivierung nicht empfohlen wird.

Da bin ich anderer Meinung, es gibt use cases wo das schon sinn macht.

Man könnte das Problem mit dem aof wie folgt lösen:

Backup:
- vor dem packen durch backitup muss `redis-cli bgsave` ausgeführt werden, dann wird das *.aof file in einem *.rdb file gespeichert
- danach kann dann backitup nur das *.rdb file sichern, evtl. muss hier noch davor lastModified des *.rdb file geprüft werden, da der prozess async läuft

Restore:
- *.rdb file in redis ordner kopieren
- danach muss der befehl `redis-cli bgrewriteaof` ausgeführt werden, um das backup in das *.aof file zurück zu spielen, evtl. muss hier noch lastModified geprüft werden, da der prozess async läuft

Grundsätzlich dürfte backitup nur *.rdb files behandeln, d.h. bei angabe eines Ordners sollte nur die *.rdb files dort mit in das backup einbezogen werden

Könntest du diesen Mechanismus implementieren?

**Comment by Scrounger** [comment]
Ich hab noch ein bissle getestet. Wenn ich tar direkt über die console ausführe, kann auch das *.aof file mit gepackt werden. Es kommt halt eine Fehler Meldung:
```
root@ioBroker:/mnt/lxcshare# tar -czvf test.tar.gz /var/lib/redis/
tar: Removing leading `/' from member names
/var/lib/redis/
/var/lib/redis/appendonly.aof
tar: /var/lib/redis/appendonly.aof: file changed as we read it
/var/lib/redis/dump.rdb
```

Hab das gleiche mit der tar npm lib getestet, die du in deinem skript verwendest. Das funktioniert zwar, aber das erzeugte file ist dann korrupt.

gleichen versuch mit der lib [node-tar](https://www.npmjs.com/package/tar) durchgeführt und damit geht es. Evtl. reicht hier schon eine andere lib zu verwenden?

**Comment by Scrounger** [comment]
Noch weiter getestet :-)

**Comment by simatec** [comment]
Gib mal den kompletten Dateipfad in Backitup an inkl. der rdb

**Comment by Scrounger** [comment]
> Gib mal den kompletten Dateipfad in Backitup an inkl. der rdb

das versteht ich nicht, dann wird ja nur das *.rdb file mit einbezogen. Mir geht es aber um das *.aof file. Und das geht nicht mit verwendung gzip, da das *.aof file paralell von redis weiter beschrieben wird.

**Comment by simatec** [comment]
Kannst du bitte mal die DEV Version testen ...
Bitte über Github mit folgenden Link installieren und im Anschluss einen Upload machen

https://github.com/simatec/ioBroker.backitup/tarball/dev

**Comment by Scrounger** [comment]
Habs getestet, folgende Fehlermeldung kommt

```
2021-02-23 08:49:08.588  - [34mdebug[39m: backitup.0 (1655) [iobroker/redis] Start Redis Backup ...
2021-02-23 08:49:08.618  - [34mdebug[39m: backitup.0 (1655) [iobroker/redis] The following files were found for the backup: appendonly.aof,dump.rdb
2021-02-23 08:49:10.376  - [31merror[39m: backitup.0 (1655) uncaught exception: did not encounter expected EOF
2021-02-23 08:49:10.376  - [31merror[39m: backitup.0 (1655) Error: did not encounter expected EOF
    at Object.[onread] (/opt/iobroker/node_modules/tar/lib/write-entry.js:247:18)
    at /opt/iobroker/node_modules/tar/lib/write-entry.js:229:19
    at FSReqCallback.wrapper [as oncomplete] (fs.js:520:5)
```

Es wird eine *.tar file im backups folder erzeugt, aber die ist korrupt mit Fehlermeldung EOF.

Ist exakt die gleiche Fehlermeldung die ich auch beim meinen Test oben bekommen habe. Ursache dafür ist der zeitgleiche Zugriff mit redis und gleichzeitiger verwendung von gzip beim erstellen des archivs

**Comment by simatec** [comment]
Sehr komisch ... Ich habe die lib "node-tar" verwendet, die bei dir ja funktioniert hat ... Oder hast du dort gzip deaktiviert

**Comment by Scrounger** [comment]
hatte dort gzip aktiviert, sorry das hab ich oben nicht sauber beschrieben.

Denke am einfachsten wäre es wirklich, wenn du erst alle Dateien aus dem redis ordner in ein temp verzeichnis kopierst und anschließend tra drüber laufen lässt. das hat in meinen test funktioniert

**Comment by simatec** [comment]
schaue mal bitte auf die aktuelle DEV-Version ...
Hab es noch einmal umgebaut. 

https://github.com/simatec/ioBroker.backitup/tarball/dev

Interessant wäre in dem Zuge auch der restore von redis

**Comment by Scrounger** [comment]
Funktioniert leider nicht, folgende Fehlermeldung kommt:

```
2021-02-24 11:15:01.175  - [34mdebug[39m: backitup.0 (1481) [iobroker/redis] Start Redis Backup ...
2021-02-24 11:15:01.175  - [34mdebug[39m: backitup.0 (1481) [iobroker/redis] Try deleting the old redis tmp directory: "/opt/iobroker/backups/redistmp"
2021-02-24 11:15:01.228  - [34mdebug[39m: backitup.0 (1481) [iobroker/redis] old redis tmp directory "/opt/iobroker/backups/redistmp" successfully deleted
2021-02-24 11:15:01.229  - [34mdebug[39m: backitup.0 (1481) [iobroker/redis] Created redistmp directory
2021-02-24 11:15:01.886  - [34mdebug[39m: backitup.0 (1481) [iobroker/redis] The following files were found for the backup: appendonly.aof,dump.rdb
2021-02-24 11:15:02.858  - [31merror[39m: backitup.0 (1481) uncaught exception: did not encounter expected EOF
2021-02-24 11:15:02.862  - [31merror[39m: backitup.0 (1481) Error: did not encounter expected EOF
    at Object.[onread] (/opt/iobroker/node_modules/tar/lib/write-entry.js:247:18)
    at /opt/iobroker/node_modules/tar/lib/write-entry.js:229:19
    at FSReqCallback.wrapper [as oncomplete] (fs.js:520:5)
2021-02-24 11:15:02.862  - [31merror[39m: backitup.0 (1481) Exception-Code: EOF: did not encounter expected EOF
2021-02-24 11:15:02.874  - [32minfo[39m: backitup.0 (1481) cleaned everything up...
```

**Comment by simatec** [comment]
So das hast du jetzt davon und bist mein Versuchskaninchen ... :-)
Teste mal bitte den aktuellen Dev-Branch ... Ich verwende nun ein Copy Variante und kein readstream / writestream

**Comment by Scrounger** [comment]
Funktioniert leider nicht, folgende Fehlermeldung kommt:

```
2021-03-01 08:04:31.999  - [34mdebug[39m: backitup.0 (1624) Backup has started ...
2021-03-01 08:04:33.537  - [34mdebug[39m: backitup.0 (1624) [iobroker/iobroker] host.devBroker 12129 states saved
2021-03-01 08:04:33.562  - [34mdebug[39m: backitup.0 (1624) [iobroker/iobroker] host.devBroker 10230 objects saved
2021-03-01 08:04:37.318  - [34mdebug[39m: backitup.0 (1624) [iobroker/iobroker] Backup created: /opt/iobroker/backups/iobroker_2021_03_01-08_04_32_backupiobroker.tar.gz
2021-03-01 08:04:38.335  - [34mdebug[39m: backitup.0 (1624) [iobroker/iobroker] done
2021-03-01 08:04:38.936  - [34mdebug[39m: backitup.0 (1624) [iobroker/redis] Start Redis Backup ...
2021-03-01 08:04:38.937  - [34mdebug[39m: backitup.0 (1624) [iobroker/redis] Try deleting the old redis tmp directory: "/opt/iobroker/backups/redistmp"
2021-03-01 08:04:38.956  - [34mdebug[39m: backitup.0 (1624) [iobroker/redis] old redis tmp directory "/opt/iobroker/backups/redistmp" successfully deleted
2021-03-01 08:04:38.957  - [34mdebug[39m: backitup.0 (1624) [iobroker/redis] Created redistmp directory
2021-03-01 08:04:39.115  - [34mdebug[39m: backitup.0 (1624) [iobroker/redis] The following files were found for the backup: appendonly.aof,dump.rdb
2021-03-01 08:04:40.982  - [34mdebug[39m: backitup.0 (1624) [iobroker/redis] The following files were found for the backup: appendonly.aof,dump.rdb
2021-03-01 08:04:41.129  - [31merror[39m: backitup.0 (1624) uncaught exception: did not encounter expected EOF
2021-03-01 08:04:41.132  - [31merror[39m: backitup.0 (1624) Error: did not encounter expected EOF
    at Object.[onread] (/opt/iobroker/node_modules/tar/lib/write-entry.js:247:18)
    at /opt/iobroker/node_modules/tar/lib/write-entry.js:229:19
    at FSReqCallback.wrapper [as oncomplete] (fs.js:520:5)
2021-03-01 08:04:41.132  - [31merror[39m: backitup.0 (1624) Exception-Code: EOF: did not encounter expected EOF
2021-03-01 08:04:42.073  - [32minfo[39m: backitup.0 (1624) cleaned everything up...
2021-03-01 08:04:42.074  - [32minfo[39m: backitup.0 (1624) terminating
2021-03-01 08:04:42.074  - [34mdebug[39m: backitup.0 (1624) Plugin sentry destroyed
2021-03-01 08:04:42.075  - [33mwarn[39m: backitup.0 (1624) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-03-01 08:04:42.198  - [31merror[39m: host.devBroker Caught by controller[0]: Error: did not encounter expected EOF
2021-03-01 08:04:42.198  - [31merror[39m: host.devBroker Caught by controller[0]:     at Object.[onread] (/opt/iobroker/node_modules/tar/lib/write-entry.js:247:18)
2021-03-01 08:04:42.199  - [31merror[39m: host.devBroker Caught by controller[0]:     at /opt/iobroker/node_modules/tar/lib/write-entry.js:229:19
2021-03-01 08:04:42.199  - [31merror[39m: host.devBroker Caught by controller[0]:     at FSReqCallback.wrapper [as oncomplete] (fs.js:520:5)
2021-03-01 08:04:42.199  - [31merror[39m: host.devBroker instance system.adapter.backitup.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2021-03-01 08:04:42.199  - [32minfo[39m: host.devBroker Restart adapter system.adapter.backitup.0 because enabled
```

**Comment by simatec** [comment]
Wird mit dem Befehl `redis-cli bgsave` ein weiterer rdb File erzeugt, oder werden die Daten mit in die dump.rdb geschrieben?

**Comment by simatec** [comment]
Ich habe nun mal zum testen in der Beta 2.0.2 auf dem Dev-Branch `redis-cli save` hinzugefügt.
Da ich aof selber nicht testen kann, müsstest du mal schauen, ob es nun tut.
Ich kann leider auch nicht sagen, ob mit save in die dump.rdb geschrieben wird, oder ob für aof eine weitere rdb angelegt wird.
Die Info benötige ich mal noch von dir, damit ich das dann ggfs. noch anpassen kann.

**Comment by simatec** [comment]
redis-cli save ist nun beim Backup als Option in der Config auswählbar und wird auch beim restore berücksichtigt.
Ich pushe es in der Version 2.0.3 ins latest und schließe hier somit den Issue.

**Comment by muchul** [comment]
tja.. war wohl zu erwarten dass irgendwann jemand kommt der das abschaltbar han möchte:
Bei mir wird die gesamte VM einmal unter Proxmox und dann noch auf einem Proxmox Backup Server(zweites Gerät) zusätzlich gesichert und daher wird diese Meldung nicht benötigt.
Gerade wenn ich am Testen bin, kann es sein das ich mehrmals in den Adapter rein muss, dann ist die Meldung aber etwas "überflüssig".
Könnte es Abschaltbar gemacht werden? 
Von mir aus auch gegen Notarielle Bestätigung?

**Comment by simatec** [comment]
Was willst du mir damit sagen? Was für eine Meldung?? Hier geht es um eine ewig alte Version und das Issue wurde bereits vor 2 1/2 Jahren geschlossen...
