### ISSUE TITLE
Unhandled promise rejection: Rate Limit Exceeded

### ISSUE THREAD

**Issue by patrickbs96** [simatec/ioBroker.backitup#458]
**Describe the bug**  
Fehlermeldung beim Upload des Backups nach Google Drive.
Tritt in unregelmäßigen Abständen auf. Vermutlich immer dann, wenn es zum `Rate Limit Exceeded` Fehler kommt.

**To Reproduce**  
- Random

**Expected behavior**  
No unhandled error.

**Screenshots & Logfiles**  
```
2021-04-08 02:00:32.844 - error: backitup.0 (12249) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
--
2021-04-08 02:00:32.853 - error: backitup.0 (12249) unhandled promise rejection: Rate Limit Exceeded
2021-04-08 02:00:32.933 - error: backitup.0 (12249) Error: Rate Limit Exceeded
at Gaxios._request (/opt/iobroker/node_modules/gaxios/src/gaxios.ts:158:15)
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at OAuth2Client.requestAsync (/opt/iobroker/node_modules/google-auth-library/build/src/auth/oauth2client.js:343:18)
2021-04-08 02:00:32.933 - error: backitup.0 (12249) Exception-Code: 403: Rate Limit Exceeded
2021-04-08 02:00:33.663 - error: host.raspberrypi Caught by controller[1]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2021-04-08 02:00:33.672 - error: host.raspberrypi Caught by controller[2]: Error: Rate Limit Exceeded
2021-04-08 02:00:33.672 - error: host.raspberrypi Caught by controller[2]: at Gaxios._request (/opt/iobroker/node_modules/gaxios/src/gaxios.ts:158:15)
2021-04-08 02:00:33.673 - error: host.raspberrypi Caught by controller[2]: at runMicrotasks ()
2021-04-08 02:00:33.673 - error: host.raspberrypi Caught by controller[2]: at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-04-08 02:00:33.673 - error: host.raspberrypi Caught by controller[2]: at OAuth2Client.requestAsync (/opt/iobroker/node_modules/google-auth-library/build/src/auth/oauth2client.js:343:18)
2021-04-08 02:00:33.674 - error: host.raspberrypi instance system.adapter.backitup.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
```

**Versions:**  
 - Adapter version: <2.1.0>
 - JS-Controller version: <3.2.16>
 - Node version: <14.15.3>
 - Operating system: <Raspberry Pi 4 - Debian>

**Additional context**

**Comment by simatec** [comment]
Das Problem liegt leider bei Google. 
Um 2 Uhr Nachts scheinen die Server überlastet. Nimm mal eine krumme Zeit. Bsp.  01:23 Uhr

**Comment by patrickbs96** [comment]
Habe ich angepasst, werde ich mal mit der Einstellung testen.

Wäre es denn möglich, dass du den Fehler abfängst? Im Log könnte dann nur ein Hinweis darauf erscheinen mit dem Tipp, der Änderung des Zeitpunkts. Oder gegebenenfalls den Upload zu einem späteren Zeitpunkt erneut versuchen?

**Comment by simatec** [comment]
Wir haben schon versucht den Fehler abzufangen. Der kommt aber aus der Google Api. Ein Issue ist dort schon ne ganze Weile offen.
