### ISSUE TITLE
Google Drive error

### ISSUE THREAD

**Issue by Z3nto** [simatec/ioBroker.backitup#513]
Hi,

ich hab vor ein paar tagen meine ioBroker instanz auf einen anderen Server umgezogen und seit dem funktioniert der Google Drive zugriff nicht mehr. Ich hab den Adapter auch schonmal entfernt und auch die oauth Rechte im google Account entzogen, dann komplett neu konfiguriert, aber der Fehler ist geblieben.

Installierte Version ist v2.1.13 auf ioBroker v5.1.9.

Wenn ich auf "Backup now" klicke, endet der Dialog mit:
```
[DEBUG] [googledrive] - Google Drive: Copy iobroker_2021_06_18-08_19_39_backupiobroker.tar.gz...
[DEBUG] [googledrive] start with {"type":"storage","source":"googledrive","debugging":true,"deleteOldBackup":true,"accessJson":"****","ownDir":false,"dir":"/backupDir","dirMinimal":"/backupDir/iobroker","deleteBackupAfter":0}
```

Folgendes sieht man dann im Log:
```
backitup.0 | 2021-06-18 08:19:45.050 | error | Exception-Code: 400: invalid_request
backitup.0 | 2021-06-18 08:19:45.050 | error | Error: invalid_request at Gaxios._request (/opt/iobroker/node_modules/gaxios/build/src/gaxios.js:129:23) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async OAuth2Client.refreshTokenNoCache (/opt/iobroker/node_modules/google-auth-library/build/src/auth/oauth2client.js:174:21) at async OAuth2Client.getRequestMetadataAsync (/opt/iobroker/node_modules/google-auth-library/build/src/auth/oauth2client.js:261:17) at async OAuth2Client.requestAsync (/opt/iobroker/node_modules/google-auth-library/build/src/auth/oauth2client.js:334:23)
backitup.0 | 2021-06-18 08:19:45.050 | error | unhandled promise rejection: invalid_request
backitup.0 | 2021-06-18 08:19:45.049 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
```

Wenn ich bei Restore auf "Get Backups" klicke, bekomm ich ein Error Popup mit einem JSON object:
```json
{
   "response":{
      "config":{
         "method":"POST",
         "url":"https://oauth2.googleapis.com/token",
         "data":"refresh_token=xxxxxxx&client_id=&client_secret=&grant_type=refresh_token",
         "headers":{
            "Content-Type":"application/x-www-form-urlencoded",
            "User-Agent":"google-api-nodejs-client/7.1.2",
            "x-goog-api-client":"gl-node/12.22.1 auth/7.1.2",
            "Accept":"application/json"
         },
         "body":"refresh_token=xxxxx&client_id=&client_secret=&grant_type=refresh_token",
         "responseType":"json"
      },
      "data":{
         "error":"invalid_request",
         "error_description":"Could not determine client ID from request."
      },
      "headers":{
         "alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"",
         "cache-control":"no-cache, no-store, max-age=0, must-revalidate",
         "connection":"close",
         "content-encoding":"gzip",
         "content-type":"application/json; charset=utf-8",
         "date":"Fri, 18 Jun 2021 06:12:12 GMT",
         "expires":"Mon, 01 Jan 1990 00:00:00 GMT",
         "pragma":"no-cache",
         "server":"scaffolding on HTTPServer2",
         "transfer-encoding":"chunked",
         "vary":"Origin, X-Origin, Referer",
         "x-content-type-options":"nosniff",
         "x-frame-options":"SAMEORIGIN",
         "x-xss-protection":"0"
      },
      "status":400,
      "statusText":"Bad Request",
      "request":{
         "responseURL":"https://oauth2.googleapis.com/token"
      }
   },
   "config":{
      "method":"POST",
      "url":"https://oauth2.googleapis.com/token",
      "data":"refresh_token=xxxxx&client_id=&client_secret=&grant_type=refresh_token",
      "headers":{
         "Content-Type":"application/x-www-form-urlencoded",
         "User-Agent":"google-api-nodejs-client/7.1.2",
         "x-goog-api-client":"gl-node/12.22.1 auth/7.1.2",
         "Accept":"application/json"
      },
      "body":"refresh_token=xxxxx&client_id=&client_secret=&grant_type=refresh_token",
      "responseType":"json"
   },
   "code":"400"
}
```

Im log gibts dann nur ein 
```
Error: invalid_request 
```

Irgendwelche Ideen was ich tun kann?

Dank und Gruß
Z3nto

**Comment by simatec** [comment]
Da scheint irgendwas am npm Packet nicht zu laufen.
Google Drive selber funktioniert mit 2.1.13 problemlos

![image](https://user-images.githubusercontent.com/39792461/122520571-0a8f0300-d014-11eb-9d80-f9a2bb4c5e45.png)

Versuche mal folgendes:

`npm rebuild backitup`

Sollte dies nicht gehen, den Adapter mal in den Instanzen und in den Adaptern deinstallieren und iobroker im Anschluss mal durchstarten.
Dann einfach neu installieren, damit alle Abhängigkeiten sauber installiert werden

**Comment by Z3nto** [comment]
Hab ich jetzt in alles möglichen varianten versucht, brachte leider keinen erfolg.
Laut npm sind die dependecies installiert.

Noch eine Idee?

**Comment by simatec** [comment]
Dein Fehlerlog ist in der Ausgabe zu sehen ...

`"error_description":"Could not determine client ID from request."`

Ich würde versuchen, den Token komplett neu zu generieren und auch prüfen, ob backitup auf deinen GoogleDrive Konto die richtigen Zugriffsrechte hat
