### ISSUE TITLE
Error thrown when zigbee backup is restored

### ISSUE THREAD

**Issue by asgothian** [simatec/ioBroker.backitup#522]
**Describe the bug**  
When a zigbee backup is restored, the zigbee adapter is terminated. Before the adapter is able to terminate cleanly, an error is thrown

**To Reproduce**  
1. Go to 'restore'
2. Select any zigbee backup
3. Select restore
4. See error pop up in the log (no error is raised in the backitup adapter)

**Expected behavior**  
The expected behavior is for the backitup adapter to wait with doing any fs related tasks until the adapter and all its libraries have been successfully terminated. The error thrown leads me to believe that this is not the case. I suspect that this may in some cases lead to restored zigbee backups being overwritten by the zigbee library which has not successfully shut down at the time the backitup adapter performs the restore.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

Snippet 1: zigbee adapter termination via restore function of backitup adapter

```
2021-07-29 17:52:40.831  - info: host.tinkerboard instance "system.adapter.zigbee.1" disabled via .alive
2021-07-29 17:52:40.845  - info: host.tinkerboard "system.adapter.zigbee.1" disabled
2021-07-29 17:52:40.847  - info: host.tinkerboard stopInstance system.adapter.zigbee.1 (force=false, process=true)
2021-07-29 17:52:40.850  - info: host.tinkerboard stopInstance system.adapter.zigbee.1 send kill signal
2021-07-29 17:52:40.854  - info: zigbee.1 (23494) Got terminate signal TERMINATE_YOURSELF
2021-07-29 17:52:40.856  - info: zigbee.1 (23494) cleaned everything up...
2021-07-29 17:52:40.859  - info: zigbee.1 (23494) Zigbee: disabling joining new devices.
2021-07-29 17:52:41.052  - error: zigbee.1 (23494) Failed to stop zigbee (Error: ENOENT: no such file or directory, open '/opt/iobroker/iobroker-data/zigbee_1/shepherd.db.tmp'
    at Object.openSync (fs.js:462:3)
    at Object.writeFileSync (fs.js:1384:35)
    at Database.write (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/database.ts:79:12)
    at Database.update (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/database.ts:48:14)
    at Device.save (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/device.ts:273:25)
    at Controller.databaseSave (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/controller.ts:290:20)
    at Controller.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/controller.ts:268:14)
    at Generator.next (<anonymous>)
    at /opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:27:71
    at new Promise (<anonymous>))
2021-07-29 17:52:41.055  - info: zigbee.1 (23494) terminating
2021-07-29 17:52:41.057  - info: zigbee.1 (23494) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason

```

Snippet2: zigbee adapter termination via manual change of "system.adapter.zigbee.1.alive" to false

```
2021-07-29 17:55:38.420  - info: host.tinkerboard instance "system.adapter.zigbee.1" disabled via .alive
2021-07-29 17:55:38.452  - info: host.tinkerboard "system.adapter.zigbee.1" disabled
2021-07-29 17:55:38.457  - info: host.tinkerboard stopInstance system.adapter.zigbee.1 (force=false, process=true)
2021-07-29 17:55:38.461  - info: host.tinkerboard stopInstance system.adapter.zigbee.1 send kill signal
2021-07-29 17:55:38.471  - info: zigbee.1 (23547) Got terminate signal TERMINATE_YOURSELF
2021-07-29 17:55:38.475  - info: zigbee.1 (23547) cleaned everything up...
2021-07-29 17:55:38.482  - info: zigbee.1 (23547) Zigbee: disabling joining new devices.
2021-07-29 17:55:38.842  - info: zigbee.1 (23547) terminating
2021-07-29 17:55:38.846  - info: zigbee.1 (23547) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2021-07-29 17:55:39.414  - info: host.tinkerboard instance system.adapter.zigbee.1 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)

```
**Versions:**  
 - Adapter version: 2.1.13
 - Zigbee adapter version: 1.5.6
 - JS-Controller version: 3.1.6
 - Node version:12.22.2
 - Operating system: raspbian (on tinkerboard)

**Comment by simatec** [comment]
Is the zigbee instance on the master on which backitup is also running or is the instance on a slave?

**Comment by asgothian** [comment]
This is on a single host - no master/slave configuration.

**Comment by simatec** [comment]
Can you please test version 2.1.15
