### ISSUE TITLE
Backup-Adapter erzeugt Fehler

### ISSUE THREAD

**Issue by Siggi0904** [simatec/ioBroker.backitup#736]
Hallo,

seit zwei Tagen läuft bei mir eine Fehlermeldung auf, wenn das Backup über den Backitup-Adapter läuft. Ich nutze die aktuelle Stable 2.4.10. mit nodejs 16.16.0 mit npm 8.11.0.
Das System steht auf Stable.

Das Backup der Scripts und das Backup der mySQL DB laufen sauber durch.

Der Fehler beim iobroker-backup:
```
[ERROR] [iobroker] - node:internal/bootstrap/switches/does_own_process_state:126
    cachedCwd = rawMethods.cwd();
                           ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at Object.process.cwd (/opt/iobroker/node_modules/graceful-fs/polyfills.js:10:19)
    at fe.Yargs (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/yargs/build/index.cjs:1:61166)
    at Argv (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/yargs/index.cjs:12:16)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/yargs/index.cjs:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
```

**Comment by simatec** [comment]
Starte mal bitte dein System einmal neu

**Comment by Siggi0904** [comment]
Super, hat geholfen.

Kann das bei kommenden Updates auch wieder auftreten?

**Comment by simatec** [comment]
Ich habe diese Meldung selber auch schon gehabt. Kann es aber nicht ganz deuten. 
Eventuell müsste man da mal ein Issue im js-controller aufmachen. 
könnte sein, dass es der Fehler dort entsteht. 
Backitup nutzt ja am Ende für das Backup den js-controller.

**Comment by Siggi0904** [comment]
@simatec Ich habe den gleichen Fehler heute wieder, obwohl ich nichts geändert habe.

Fehler:
```
[ERROR] [iobroker] - node:internal/bootstrap/switches/does_own_process_state:126
    cachedCwd = rawMethods.cwd();
                           ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at Object.process.cwd (/opt/iobroker/node_modules/graceful-fs/polyfills.js:10:19)
    at fe.Yargs (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/yargs/build/index.cjs:1:61166)
    at Argv (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/yargs/index.cjs:12:16)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/yargs/index.cjs:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}

[DEBUG] [iobroker] - done
```

**Comment by simatec** [comment]
Das scheint ein Problem mit node zu sein und wurde bereits im js-controller als Issue erfasst. 
Bitte starte einmal dein System komplett neu. 
Nach einem Reboot ist der Fehler behoben.

**Comment by Siggi0904** [comment]
Okay, hoffentlich findet sich zeitnah eine Lösung.

Denn ich muste ja schon einmal wegen dem Bug neu starten.

**Comment by simatec** [comment]
Wenn der Bug wieder auftreten sollte, versuche mal ein `iob backup` Über CLI

**Comment by Siggi0904** [comment]
Hi,
nach dem heutigem Update einiger Adaapter tritt der Fehler wieder auf.
Der Aufruf von `iob Backup` läuft super durch.

Die Ausgabe:
```
iobroker@iobroker:~$ cd /opt/iobroker/
iobroker@iobroker:/opt/iobroker$ iob backup
host.iobroker 7859 states saved
host.iobroker 9441 objects saved
Backup created: /opt/iobroker/backups/2022_09_17-14_15_45_backupiobroker.tar.gz
iobroker@iobroker:/opt/iobroker$
```

Gibt es schon eine Lösung?

**Comment by simatec** [comment]
Kannst du mal bitte alle Infos zu deinem System zusammenschreiben. 
Wir schauen gerade, wo es herkommen kann und vermuten das Problem auf der Systemseite. 

Darum mal die Bitte alles an Infos vom System posten.

**Comment by Siggi0904** [comment]
Das System ist eine Proxmox VM mit Debian Bullseye X64 und IOBroker im Stable Zweig.
System und IO-Broker sind up-to-date.

Welche Angaben benötigst du zusätzlich?

**Comment by simatec** [comment]
Also die Googlesuche spuckt sehr viel zu dem Fehler aus. 
Das scheint wirklich ein Systemproblem sein. 

`no such file or directory, uv_cwd`

**Comment by Siggi0904** [comment]
Ja, aber irgendwie führen alle Meldungen auf eine Lösung.
`It worked for me to close all terminal windows and open them again.`

Wird da im nodejs irgend eine Verbindung nicht richtig geschlossen,
dass das auf der Shell nicht auftritt?
Ist das evtl. irgend ein Laufzeitproblem?

**Comment by simatec** [comment]
Wir recherchieren gerade in verschiedene Richtungen. 
könnte aber durchaus sein, da es nach einem Neustart behoben ist

**Comment by Siggi0904** [comment]
https://stackoverflow.com/questions/69387345/react-native-debugger-error-enoent-no-such-file-or-directory

hier wird das löschen des Cache empfohlen.
Also irgendwas, was da im Cache gehalten wird.

**Comment by Siggi0904** [comment]
Hi,
habt ihr was gefunden? Denn nach dem heutigen Update einiger Adapter (SQL, IOT und Script Engine)
geht das Backup wieder nicht.

Was mir aufgefallen ist, ist die Frage ob bei einem Adapter-Update der Javascript-Adapter jedes mal neu startet?
Denn mir viel auf, dass nach dem Update meine node-mihome Dateien jedes mal weg sind.
Auch ist  scheinbar der Order "/opt/iobroker/node_modules/iobroker.javascript/node_modules/node-mihome/" dann weg.
Erst ein nochmaliges neu starten des Javascript-Adapters bringt den og. Ordner wieder zurück.

Danke.

**Comment by Siggi0904** [comment]
Ergänzend zu meinem Kommentar fand ich folgendes im Log nach dem nochmaligen Neustart vom Javascript-Adapater:
```
022-09-19 17:56:16.348  - info: javascript.0 (304105) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
--
2022-09-19 17:56:16.949  - info: host.iobroker instance system.adapter.javascript.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2022-09-19 17:56:19.434  - info: host.iobroker instance system.adapter.javascript.0 started with pid 367551
2022-09-19 17:56:22.316  - info:  javascript.0 (367551) starting. Version 6.0.3 in  /opt/iobroker/node_modules/iobroker.javascript, node: v16.17.0,  js-controller: 4.0.23
2022-09-19 17:56:22.470  - info: javascript.0 (367551) npm install node-mihome --omit=dev (System call)
2022-09-19 17:56:29.756  - info: javascript.0 (367551)
```

**Comment by Siggi0904** [comment]
@simatec @Apollon77 Gibt s hier schon eine Lösung.

Ich habe den seit einer Woche wieder anstehend und ich müsste wieder das System neu starten.

Dank dir.

**Comment by simatec** [comment]
Teste mal bitte die v2.5.8.
Ich habe dort versucht, dass Problem zu beheben.

**Comment by Siggi0904** [comment]
Könntest du die Version releasen?
Ich bin auf stable und würde dort auch gern bleiben. Da ich nur dieses eine Produktion-System habe.

**Comment by simatec** [comment]
Ein Release erfolgt erst nach der Testphase

**Comment by Apollon77** [comment]
@Siggi0904 In Admin kannst Du einfach "Custom install" (Expertenmodus) - "Install from npm" tab nutzen um einen adater einmalig direkt als Beta zu installieren. Musst da kein Repo wechseln

**Comment by nukleuz80** [comment]
Hallo zusammen,

ich habe seit ein paar Tagen den gleichen Fehler. Allerdings hilft kein Neustart des Adapters bzw. des gesamten Systems.
Bei jedem Backup-Versuch kommt das:

`[ERROR] [iobroker] - node:internal/bootstrap/switches/does_own_process_state:126
    cachedCwd = rawMethods.cwd();
                           ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at Object.process.cwd (/opt/iobroker/node_modules/graceful-fs/polyfills.js:10:19)
    at ue.Yargs (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/yargs/build/index.cjs:1:61846)
    at Argv (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/yargs/index.cjs:12:16)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/yargs/index.cjs:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}`

Systemsetup:

Debian 9.6.0
BackitUp: 2.5.12
JS-Controller: 4.0.24

Was kann ich tun?

PS: iobroker backup läuft durch auf der Konsole...

**Comment by simatec** [comment]
Ich würde dir erstmal raten dein System auf aktuellen Stand zu bringen. Debian 9 ist EndofLife. 
danach einen sauberen Neustart des Systems machen.

**Comment by nukleuz80** [comment]
Bin back on Track auf neuem System. Das wurde dann wohl auch mal Zeit... :)
