### ISSUE TITLE
permission error

### ISSUE THREAD

**Issue by vr6syncro** [simatec/ioBroker.backitup#76]
Moin, habe heute mein System mit dem neuen ioBroker installer neu aufgesetzt. nachdem bekomme ich folgende fehlermeldungen:

`[ERROR] [minimal] - fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/opt/iobroker/node_modules/iobroker.js-controller/tmp/backup/backup.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupBackup.js:263:24
    at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:157:27)
    at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:319:9)
    at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:244:12)
    at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
    at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:345:8)
    at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)`

**Comment by simatec** [comment]
Der Fehler kommt nicht von backitup. 
Hier liegt ein Fehler bei den rechten vor. 
Installiere iob nach der alten Methode
