### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by cburghardt** [simatec/ioBroker.backitup#809]
Version: 2.5.7
Backup via Google drive, Master is on docker

When I start the backup on the master I get the following error:

Started iobroker ...
[ERROR] [iobroker] - node:internal/bootstrap/switches/does_own_process_state:126
    cachedCwd = rawMethods.cwd();
                           ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at Object.process.cwd (/opt/iobroker/node_modules/graceful-fs/polyfills.js:10:19)
    at fe.Yargs (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/yargs/build/index.cjs:1:61304)
    at Argv (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/yargs/index.cjs:12:16)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/yargs/index.cjs:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}

And then as a result:

[iobroker/googledrive] Google Drive: File "/opt/iobroker/backups/iobroker_2022_12_03-10_05_16_backupiobroker.tar.gz" not found
--

**Comment by simatec** [comment]
Please Restart your System

**Comment by cburghardt** [comment]
I already tried that, also on previous versions. But this doesn't solve the 
issue.

Am 3. Dezember 2022 16:30:52 schrieb simatec ***@***.***>:

**Comment by simatec** [comment]
Please try `npm cache clean --force`

**Comment by cburghardt** [comment]
OK, that looks good for now. I will monitor it the next days.

**Comment by simatec** [comment]
Please Test v.2.5.8

**Comment by cburghardt** [comment]
That looks good, so far no further error messages.

Am 3. Dezember 2022 20:52:27 schrieb simatec ***@***.***>:
