### ISSUE TITLE
Seit 1.0.2 startet der Adapter nicht mehr.

### ISSUE THREAD

**Issue by kugelkopf123** [simatec/ioBroker.backitup#86]
Hallo! 

Leider startet der Adapter Backitup 1.0.2. nicht mehr in dieser Version.

NPM: 6.4.1
Node: 8.15
JS-controller: 1.5.3

`

2019-01-06 04:21:37.641 - info: backitup.0 terminating
--
2019-01-06 04:21:37.664 - error: Caught by controller[0]: { Error: ENOENT: no such file or directory, unlink '/opt/iobroker/node_modules/iobroker.backitup/lib/stopIOB.sh'
2019-01-06 04:21:37.665 - error: Caught by controller[0]: at Object.fs.unlinkSync (fs.js:1061:18)
2019-01-06 04:21:37.665 - error: Caught by controller[0]: at createBashScripts (/opt/iobroker/node_modules/iobroker.backitup/main.js:489:16)
2019-01-06 04:21:37.665 - error: Caught by controller[0]: at Adapter.main (/opt/iobroker/node_modules/iobroker.backitup/main.js:555:5)
2019-01-06 04:21:37.665 - error: Caught by controller[0]: at emitNone (events.js:106:13)
2019-01-06 04:21:37.665 - error: Caught by controller[0]: at Adapter.emit (events.js:208:7)
2019-01-06 04:21:37.665 - error: Caught by controller[0]: at initAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5290:18)
2019-01-06 04:21:37.666 - error: Caught by controller[0]: at createInstancesObjects (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:869:54)
2019-01-06 04:21:37.666 - error: Caught by controller[0]: at Immediate.createInstancesObjects [as _onImmediate] (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:830:13)
2019-01-06 04:21:37.666 - error: Caught by controller[0]: at runCallback (timers.js:814:20)
2019-01-06 04:21:37.666 - error: Caught by controller[0]: at tryOnImmediate (timers.js:768:5)
2019-01-06 04:21:37.666 - error: Caught by controller[0]: errno: -2,
2019-01-06 04:21:37.666 - error: Caught by controller[0]: code: 'ENOENT',
2019-01-06 04:21:37.666 - error: Caught by controller[0]: syscall: 'unlink',
2019-01-06 04:21:37.666 - error: Caught by controller[0]: path: '/opt/iobroker/node_modules/iobroker.backitup/lib/stopIOB.sh' }
2019-01-06 04:21:37.667 - error: host.raspi2 instance system.adapter.backitup.0 terminated with code 0 (OK)
2019-01-06 04:21:37.667 - info: host.raspi2 Restart adapter system.adapter.backitup.0 because enabled

`

**Comment by LDSign** [comment]
Hallo

Bei mir ebenso mit genau der gleichen Fehlerausgabe :(

**Comment by dontobi** [comment]
Und bei mir ist es auch so. Habe die selben Versionen wie beim Einreicher installiert.

**Comment by bergjet** [comment]
Auch bei mir.
NPM: 6.4.1
Node: 8.14
JS-controller: 1.5.3

**Comment by Kunibert-007** [comment]
Same problem:
`

host.rock64 | 2019-01-06 12:37:34.035 | error | instance system.adapter.backitup.0 terminated with code 0 (OK)
-- | -- | -- | --
host.rock64 | 2019-01-06 12:37:34.035 | error | Caught by controller[0]: at tryOnImmediate (timers.js:768:5)
host.rock64 | 2019-01-06 12:37:34.034 | error | Caught by controller[0]: at runCallback (timers.js:814:20)
host.rock64 | 2019-01-06 12:37:34.034 | error | Caught by controller[0]: at Immediate.createInstancesObjects [as _onImmediate] (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:830:13)
host.rock64 | 2019-01-06 12:37:34.034 | error | Caught by controller[0]: at createInstancesObjects (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:869:54)
host.rock64 | 2019-01-06 12:37:34.034 | error | Caught by controller[0]: at initAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5290:18)
host.rock64 | 2019-01-06 12:37:34.033 | error | Caught by controller[0]: at Adapter.emit (events.js:208:7)
host.rock64 | 2019-01-06 12:37:34.033 | error | Caught by controller[0]: at emitNone (events.js:106:13)
host.rock64 | 2019-01-06 12:37:34.033 | error | Caught by controller[0]: at Adapter.main (/opt/iobroker/node_modules/iobroker.backitup/main.js:555:5)
host.rock64 | 2019-01-06 12:37:34.033 | error | Caught by controller[0]: at createBashScripts (/opt/iobroker/node_modules/iobroker.backitup/main.js:489:16)
host.rock64 | 2019-01-06 12:37:34.033 | error | Caught by controller[0]: at Object.fs.unlinkSync (fs.js:1061:18)
host.rock64 | 2019-01-06 12:37:34.032 | error | Caught by controller[0]: 2019-01-06 12:37:33.458 - [31merror[39m: backitup.0 Error: ENOENT: no such file or directory, unlink '/opt/iobroker/node_modules/iobroker.backitup/lib/stopIOB.sh'
host.rock64 | 2019-01-06 12:37:34.032 | error | Caught by controller[0]: 2019-01-06 12:37:33.458 - backitup.0 uncaught exception: ENOENT: no such file or directory, unlink '/opt/iobroker/node_modules/iobroker.backitup/lib/stopIOB.sh'
host.rock64 | 2019-01-06 12:37:34.032 | error | Caught by controller[0]: path: '/opt/iobroker/node_modules/iobroker.backitup/lib/stopIOB.sh' }
host.rock64 | 2019-01-06 12:37:34.031 | error | Caught by controller[0]: syscall: 'unlink',
host.rock64 | 2019-01-06 12:37:34.031 | error | Caught by controller[0]: code: 'ENOENT',
host.rock64 | 2019-01-06 12:37:34.031 | error | Caught by controller[0]: errno: -2,
host.rock64 | 2019-01-06 12:37:34.031 | error | Caught by controller[0]: at tryOnImmediate (timers.js:768:5)
host.rock64 | 2019-01-06 12:37:34.030 | error | Caught by controller[0]: at runCallback (timers.js:814:20)
host.rock64 | 2019-01-06 12:37:34.030 | error | Caught by controller[0]: at Immediate.createInstancesObjects [as _onImmediate] (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:830:13)
host.rock64 | 2019-01-06 12:37:34.030 | error | Caught by controller[0]: at createInstancesObjects (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:869:54)
host.rock64 | 2019-01-06 12:37:34.029 | error | Caught by controller[0]: at initAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5290:18)
host.rock64 | 2019-01-06 12:37:34.029 | error | Caught by controller[0]: at Adapter.emit (events.js:208:7)
host.rock64 | 2019-01-06 12:37:34.028 | error | Caught by controller[0]: at emitNone (events.js:106:13)
host.rock64 | 2019-01-06 12:37:34.028 | error | Caught by controller[0]: at Adapter.main (/opt/iobroker/node_modules/iobroker.backitup/main.js:555:5)
host.rock64 | 2019-01-06 12:37:34.028 | error | Caught by controller[0]: at createBashScripts (/opt/iobroker/node_modules/iobroker.backitup/main.js:489:16)
host.rock64 | 2019-01-06 12:37:34.027 | error | Caught by controller[0]: at Object.fs.unlinkSync (fs.js:1061:18)
host.rock64 | 2019-01-06 12:37:34.026 | error | Caught by controller[0]: { Error: ENOENT: no such file or directory, unlink '/opt/iobroker/node_modules/iobroker.backitup/lib/stopIOB.sh'
backitup.0 | 2019-01-06 12:37:33.493 | error | Error: ENOENT: no such file or directory, unlink '/opt/iobroker/node_modules/iobroker.backitup/lib/stopIOB.sh' at Object.fs.unlinkSync (fs.js:1061:18) at createBashScripts (/opt/iobroker/node_
backitup.0 | 2019-01-06 12:37:33.493 | error | uncaught exception: ENOENT: no such file or directory, unlink '/opt/iobroker/node_modules/iobroker.backitup/lib/stopIOB.sh'

`
NPM 6.4.1
Habe auch Backitup komplett neu installiert und alle Adapter neu kompiliiert aber leider ohne Erfolg, der Fehler bleibt

**Comment by simatec** [comment]
Ist mit Version 1.0.3 gefixt
