### ISSUE TITLE
Getting very often Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by ioBroker22** [simatec/ioBroker.backitup#954]
**Describe the bug**  
I have enabled the Backup for everyday. But most of the time it gets with this error interrupted and exits.

**To Reproduce**  
Let History make some logs of your datapoints. Activate the auto-delete-function for old entrys in History. Enable the History Backup function in backitup. Wait for the coincidence that one entry will be deleted, just seconds before backitup wants to backup this entry. It will exit the process.

**Expected behavior**  
Ignore the missing file and continue the backup.

**Screenshots & Logfiles**  
Error today:
```
2023-05-27 03:46:04.082 - info: history.0 (744) Delete old history "/media/usb1/history/20230518/history.Steckdose110_Alive.json"
2023-05-27 03:46:32.864 - error: backitup.0 (1344) [iobroker/historyDB] Error: ENOENT: no such file or directory, lstat '/media/usb1/history/20230518/history.Steckdose110_Alive.json'
2023-05-27 03:46:32.882 - error: backitup.0 (1344) [iobroker] Error: ENOENT: no such file or directory, lstat '/media/usb1/history/20230518/history.Steckdose110_Alive.json'
```
Error some days ago:
```
2023-05-25 03:46:03.976 - info: history.0 (744) Delete old history "/media/usb1/history/20230516/history.Steckdose110_Alive.json"
2023-05-25 03:46:06.208 - error: backitup.0 (1344) [iobroker/historyDB] Error: ENOENT: no such file or directory, lstat '/media/usb1/history/20230516/history.Steckdose110_Alive.json'
2023-05-25 03:46:06.225 - error: backitup.0 (1344) [iobroker] Error: ENOENT: no such file or directory, lstat '/media/usb1/history/20230516/history.Steckdose110_Alive.json'
```
Error a few days ago:
```
2023-05-22 03:26:03.684 - info: history.0 (744) Delete old history "/media/usb1/history/20230218/history.alexa2.0.History.name.json"
2023-05-22 03:26:03.742 - info: history.0 (744) Delete old history "/media/usb1/history/20230218/history.alexa2.0.History.summary.json"
2023-05-22 03:46:03.828 - info: history.0 (744) Delete old history "/media/usb1/history/20230513/history.Steckdose110_Alive.json"
2023-05-22 03:46:11.097 - error: backitup.0 (1344) [iobroker/historyDB] Error: ENOENT: no such file or directory, lstat '/media/usb1/history/20230513/history.Steckdose110_Alive.json'
2023-05-22 03:46:11.110 - error: backitup.0 (1344) [iobroker] Error: ENOENT: no such file or directory, lstat '/media/usb1/history/20230513/history.Steckdose110_Alive.json'
```
**Versions:**  
 - Adapter version: v2.6.19
 - JS-Controller version: v4.0.24
 - Node version: v18.16.0
 - Operating system: linux/RaspberryPi

**Additional context**  
Before i enabled the auto-delete-function for old entrys in History there were no problems.

**Comment by simatec** [comment]
Please post your Config from Backitup

**Comment by ioBroker22** [comment]
[system.adapter.backitup.0.json.zip](https://github.com/simatec/ioBroker.backitup/files/11601673/system.adapter.backitup.0.json.zip)
The Feature "Email on error" doesn't work either, but this is not the biggest problem for me.

![2023-05-30_171654](https://github.com/simatec/ioBroker.backitup/assets/62349740/b69fcc15-595a-4f5d-976d-fce5e38d5b40)
![2023-05-30_171717](https://github.com/simatec/ioBroker.backitup/assets/62349740/f9c0c093-1cd4-41d1-a41a-b329c80598bb)
![2023-05-30_171733](https://github.com/simatec/ioBroker.backitup/assets/62349740/34599bb4-43af-4e1c-96e5-ab9457beb1d3)
![2023-05-30_171811](https://github.com/simatec/ioBroker.backitup/assets/62349740/4ac91869-c9ad-4061-be1f-53a0460acddd)
![2023-05-30_171824](https://github.com/simatec/ioBroker.backitup/assets/62349740/b9b74149-7def-4491-9367-96f576af0bad)
![2023-05-30_171838](https://github.com/simatec/ioBroker.backitup/assets/62349740/3f654203-9f67-461c-be36-760d6428cfbd)
![2023-05-30_171912](https://github.com/simatec/ioBroker.backitup/assets/62349740/0ef6f865-d398-4cf8-b825-2eddd23ca5f2)

**Comment by simatec** [comment]
The user "iobroker" does not have sufficient rights for your USB stick where the history data is located.

You have to adjust this so that the user "iobroker" can write, read and also delete there.

**Comment by ioBroker22** [comment]
Okay, i will try to check the rights. But are you sure? Sometimes (like yesterday the 30.5.2023 and 26.5.2023 and 21.5.2023) the backup worked fine.

**Comment by W0RSCHD** [comment]
Have the same Problem. After Backitup Instance restart, it works once.
Problem is since Update to Node 18

This is from Log from Backitup Adapter

`Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at process.cwd (/opt/iobroker/node_modules/graceful-fs/polyfills.js:10:19)
    at ue.Yargs (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/yargs/build/index.cjs:1:61943)
    at Argv (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/yargs/index.cjs:12:16)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/yargs/index.cjs:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}

Node.js v18.16.0
`

We are not allone with this issue,
https://forum.iobroker.net/topic/57108/2-5-9-fehler-existiert-backup-adapter-erzeugt-fehler/59

**Comment by simatec** [comment]
This error is current a nodejs Problem ...
